// ============================================================
// CODE ON SOCIAL SECURITY, 2020 — COMPLETE DATA FILE
// Act No. 36 of 2020 | G.S.R. 344(E) | 8 May 2026
// 164 Sections | 69 Central Rules | 30 Forms (FORM-I to XXX)
// ============================================================

const DATA_SS = {
  meta: {
    code: "ss",
    name: "Code on Social Security, 2020",
    icon: "🏦",
    act: "Act No. 36 of 2020",
    sections: 164,
    rules: 69,
    forms: 30,
    enacted: "28 Sep 2020",
    accent: "#2ECC9A",
    gsr: "G.S.R. 344(E)"
  },

  stats: [
    { num: 164,     label: "Code Sections",    sub: "14 Chapters" },
    { num: 69,      label: "Central Rules",     sub: "8 May 2026" },
    { num: 30,      label: "Prescribed Forms",  sub: "FORM-I to XXX" },
    { num: 7,       label: "Schedules",         sub: "Definitions, Lists & Factors" },
    { num: "3.25%", label: "ESI Employer Share",sub: "Employee: 0.75%" },
    { num: 5,       label: "Record Retention",  sub: "Minimum Years" }
  ],

  // ============================================================
  // 164 SECTIONS — All 14 Chapters
  // ============================================================
  sections: [
    // CHAPTER I — PRELIMINARY (Sections 1-3)
    {sec:"1", ch:"I", title:"Short title, extent, commencement and application", provision:"Code extends to whole India; different commencement dates for different provisions; voluntary EPF/ESI coverage for smaller establishments. Consolidates 9 earlier social security laws.", app:"All Establishments"},
    {sec:"2", ch:"I", title:"Definitions", provision:"Comprehensive definitions: employee, employer, wages, gig worker, platform worker, aggregator, unorganised worker, building worker, insured person, dependent, family, BOCW beneficiary, UAN, etc.", app:"All"},
    {sec:"3", ch:"I", title:"Registration and cancellation of establishment", provision:"Mandatory electronic registration via common Form-I on Shram Suvidha Portal with OSH Rules; certificate auto-generated; update within 30 days; cancellation process for closing establishments.", app:"All Establishments"},

    // CHAPTER II — SOCIAL SECURITY ORGANISATIONS (Sections 4-13)
    {sec:"4",  ch:"II", title:"Constitution of Board of Trustees of Employees' Provident Fund", provision:"Central Board composition: Chairperson, officials, State reps, employer/employee reps, CPFC ex-officio. Manages EPF Scheme, Pension Scheme, Insurance Scheme.", app:"EPF"},
    {sec:"5",  ch:"II", title:"Constitution of Employees' State Insurance Corporation", provision:"Corporation composition: Chairperson, officials, State/UT reps, employer/employee/medical reps, MPs, DG ex-officio. Manages ESI Fund and medical benefits.", app:"ESI"},
    {sec:"6",  ch:"II", title:"National Social Security Board and State Unorganised Workers' Board", provision:"National Board for unorganised/gig/platform workers policy; State Boards for implementation and monitoring; term of members 5 years.", app:"Unorganised/Gig/Platform"},
    {sec:"7",  ch:"II", title:"Constitution of State Building Workers' Welfare Boards", provision:"State-level BOCW Boards: equal Govt/employer/worker representation; welfare functions including housing, educational, health and recreational facilities.", app:"BOCW"},
    {sec:"8",  ch:"II", title:"Disqualification and removal of members", provision:"Grounds for disqualification: insolvency, conviction, default in dues, absence from meetings, incapacity; removal with show-cause opportunity.", app:"All Organisations"},
    {sec:"9",  ch:"II", title:"Procedure for transaction of business", provision:"Meeting intervals, quorum requirements, casting vote, authentication of decisions; fees and allowances for members as prescribed.", app:"All Organisations"},
    {sec:"10", ch:"II", title:"Executive Heads of Central Board and Corporation", provision:"CPFC and DG as whole-time officers; appointment conditions; cannot undertake outside work without Central Government approval.", app:"EPF/ESI"},
    {sec:"11", ch:"II", title:"Supersession of Organisations", provision:"Central/State Govt may supersede Boards/Corporations for persistent default or dysfunction; reconstitution within prescribed period.", app:"All Organisations"},
    {sec:"12", ch:"II", title:"State Board, Regional Boards, local committees", provision:"Central Govt may constitute State Boards for EPF; Corporation may appoint Regional Boards and local committees for ESI administration.", app:"EPF/ESI"},
    {sec:"13", ch:"II", title:"Entrustment of additional functions", provision:"Central Govt may assign additional social security functions to Social Security Organisations with appropriate funding arrangements.", app:"All Organisations"},

    // CHAPTER III — EMPLOYEES' PROVIDENT FUND (Sections 14-23)
    {sec:"14", ch:"III", title:"Appointment of officers of Central Board", provision:"CPFC as CEO; Financial Advisor appointed; Additional CPFCs, Regional PF Commissioners, Enforcement Officers appointed via UPSC/Board.", app:"EPF"},
    {sec:"15", ch:"III", title:"Schemes", provision:"Power to frame EPF Scheme, Employees Pension Scheme (8.33% of employer share to pension), Employees Deposit Linked Insurance Scheme (≤1% wages), other social security schemes.", app:"EPF"},
    {sec:"16", ch:"III", title:"Funds", provision:"Provident Fund: employer 10-12% + employee 10-12%; Pension Fund: 8.33% of employer contribution; Insurance Fund: ≤1% of wages as employer contribution.", app:"EPF"},
    {sec:"17", ch:"III", title:"Contribution in respect of employees and contractors", provision:"Recovery from contractors by establishment; contractor may recover employee share from wages; principal employer ultimately liable for contributions.", app:"EPF"},
    {sec:"18", ch:"III", title:"Fund to be recognised under Income-tax Act", provision:"EPF deemed recognised provident fund under Income-tax Act, 1961; contributions and interest exempt from income tax subject to limits.", app:"EPF"},
    {sec:"19", ch:"III", title:"Priority of payment of contributions over other debts", provision:"EPF dues have priority charge on establishment assets under Insolvency and Bankruptcy Code, 2016; rank above other unsecured creditors.", app:"EPF"},
    {sec:"20", ch:"III", title:"Chapter not to apply to certain establishments", provision:"Exemptions: co-operative societies with <50 workers, Govt establishments with equivalent benefits, pre-Code PF beneficiaries; voluntary coverage for others.", app:"EPF"},
    {sec:"21", ch:"III", title:"Authorising certain employers to maintain provident fund accounts", provision:"Employers with 100+ employees may maintain own PF trust accounts subject to: no defaults in last 3 years, adequate investment, worker representation in trust.", app:"EPF"},
    {sec:"22", ch:"III", title:"Transfer of accounts", provision:"PF/pension account transfer on employee movement between covered/non-covered establishments; UAN-based portability; nomination transfer.", app:"EPF"},
    {sec:"23", ch:"III", title:"Appeal to Tribunal", provision:"Appeal in FORM-I to Central Government Industrial Tribunal against EPF assessment/damages/other orders; 25% deposit required for employer appeals; ₹1,000 fee.", app:"EPF"},

    // CHAPTER IV — EMPLOYEES STATE INSURANCE CORPORATION (Sections 24-52)
    {sec:"24", ch:"IV", title:"Principal Officers and other staff", provision:"Appointment of Director General and Financial Commissioner; recruitment rules; UPSC consultation for Group A and B posts; pay scales prescribed.", app:"ESI"},
    {sec:"25", ch:"IV", title:"Employees' State Insurance Fund", provision:"All contributions, grants, donations, CSR funds credited to ESI Fund; managed by Corporation; maintained in scheduled banks/RBI.", app:"ESI"},
    {sec:"26", ch:"IV", title:"Purposes for which ESI Fund may be expended", provision:"Fund used for: payment of benefits, medical treatment, salaries of staff, hospitals, administration, audit costs, legal expenses, health promotion measures.", app:"ESI"},
    {sec:"27", ch:"IV", title:"Holding of property, etc.", provision:"Corporation may acquire/hold/transfer movable and immovable property; invest surplus funds in approved securities; raise loans with Central Govt sanction.", app:"ESI"},
    {sec:"28", ch:"IV", title:"All employees to be insured", provision:"Mandatory insurance for all employees in covered establishments; 'Insured Person' defined; registration mandatory on or before date of first employment.", app:"ESI (10+ Employees)"},
    {sec:"29", ch:"IV", title:"Contributions", provision:"Employer: 3.25% of wages; Employee: 0.75% of wages; both rounded to next higher rupee; PwD employee: employer share waived for 3 years; contribution period: 6 months.", app:"ESI"},
    {sec:"30", ch:"IV", title:"Administrative expenses", provision:"Administrative expenses of Corporation capped at prescribed percentage of total revenue income; excess requires Central Government approval.", app:"ESI"},
    {sec:"31", ch:"IV", title:"Provisions as to payment of contributions by employer", provision:"Employer pays both shares; may recover employee share from wages; contractor liability; principal employer responsible if contractor defaults.", app:"ESI"},
    {sec:"32", ch:"IV", title:"Benefits", provision:"Sickness benefit (78 contribution days, 70% of SBR), maternity benefit, temporary/permanent disablement benefit, dependants' benefit, medical benefit, funeral expenses ₹20,000, rehabilitation allowance.", app:"ESI"},
    {sec:"33", ch:"IV", title:"Corporation's power to promote measures for health", provision:"Corporation may spend prescribed percentage of income on health promotion, welfare measures and re-employment facilities for insured persons.", app:"ESI"},
    {sec:"34", ch:"IV", title:"Presumption as to accident arising in course of employment", provision:"Accident during employment presumed employment-related; commuting accidents covered if nexus established; employer to rebut presumption.", app:"ESI"},
    {sec:"35", ch:"IV", title:"Accidents happening while acting in breach of law", provision:"Accident still deemed employment-related if act done for employer's business even if in breach of law or regulations.", app:"ESI"},
    {sec:"36", ch:"IV", title:"Occupational disease", provision:"Diseases in Third Schedule deemed employment injury if contracted during specified employment; medical board certification required.", app:"ESI"},
    {sec:"37", ch:"IV", title:"References to medical board", provision:"Medical Board determines disablement questions; review provisions; appeal to Medical Appeal Tribunal; further appeal to Employees' Insurance Court.", app:"ESI"},
    {sec:"38", ch:"IV", title:"Dependants' benefit", provision:"Benefit to dependants of deceased insured person: widow, children, parents; rates and periods prescribed; reviewable on change in circumstances.", app:"ESI"},
    {sec:"39", ch:"IV", title:"Medical benefit", provision:"Insured person and spouse/family entitled to medical treatment; outpatient and inpatient care; continuation for 91 days post-employment on certain conditions.", app:"ESI"},
    {sec:"40", ch:"IV", title:"Provision of medical treatment by State Government or by Corporation", provision:"State Govt provides medical care; cost-sharing agreement with Corporation; Corporation may establish and manage hospitals directly with State consent.", app:"ESI"},
    {sec:"41", ch:"IV", title:"General provisions as to benefits", provision:"No commutation of benefits except as prescribed; no double benefits simultaneously; recovery of wrongly paid benefits; assignment or attachment of benefits prohibited.", app:"ESI"},
    {sec:"42", ch:"IV", title:"Corporation's rights when employer fails to register", provision:"Corporation may pay benefits to unregistered employees and recover capitalised value from defaulting employer with interest and damages.", app:"ESI"},
    {sec:"43", ch:"IV", title:"Liability for excessive sickness benefit", provision:"Corporation may claim excess sickness benefit costs from employer if due to insanitary conditions or failure to maintain safe workplace.", app:"ESI"},
    {sec:"44", ch:"IV", title:"Scheme for other beneficiaries", provision:"Central Govt may frame scheme for non-employees to utilise underutilised ESI hospitals on payment of user charges.", app:"ESI"},
    {sec:"45", ch:"IV", title:"Schemes for unorganised workers, gig workers and platform workers", provision:"Central Govt may frame ESI-benefit schemes for unorganised/gig/platform workers; contribution rates specified; State Govts co-fund schemes.", app:"ESI/Gig/Unorganised"},
    {sec:"46", ch:"IV", title:"Exemption of government establishments", provision:"Appropriate Govt may exempt govt/local authority establishments if employees receive substantially similar or superior benefits under other schemes.", app:"ESI"},
    {sec:"47", ch:"IV", title:"Contributions due to Corporation to have priority", provision:"ESI dues have priority charge on establishment assets under Insolvency and Bankruptcy Code, 2016; Corporation's claim ranks above other unsecured creditors.", app:"ESI"},
    {sec:"48", ch:"IV", title:"Constitution of Employees Insurance Court", provision:"State Govt constitutes EI Courts; qualification: judicial officer or 5+ years legal practice; territorial jurisdiction prescribed.", app:"ESI"},
    {sec:"49", ch:"IV", title:"Matters to be decided by Employees Insurance Court", provision:"EI Court decides: employee/wages/contribution rate disputes, benefit rights, recovery claims, all disputes arising under Chapter IV.", app:"ESI"},
    {sec:"50", ch:"IV", title:"Powers of Employees Insurance Court", provision:"EI Court has Civil Court powers for summons, evidence, oath, production of documents; procedure prescribed by State Government.", app:"ESI"},
    {sec:"51", ch:"IV", title:"Proceedings of Employees Insurance Courts", provision:"Limitation: 3 years from cause of action; legal practitioner representation allowed; reference to High Court on question of law.", app:"ESI"},
    {sec:"52", ch:"IV", title:"Appeal to High Court", provision:"Appeal to High Court only on substantial question of law; 60-day limitation; Limitation Act applies for condonation of delay.", app:"ESI"},

    // CHAPTER V — GRATUITY (Sections 53-58)
    {sec:"53", ch:"V", title:"Payment of gratuity", provision:"Gratuity payable after 5 years continuous service on superannuation, retirement, resignation, death or disablement; 15 days' wages per completed year (above 6 months); cap as notified; fixed-term employees eligible on completion of 1 year.", app:"Gratuity"},
    {sec:"54", ch:"V", title:"Continuous service", provision:"Uninterrupted service including leave, lay-off, maternity, strike, lockout; deemed continuous if 190 days worked in 12 months (mine) or 240 days (others).", app:"Gratuity"},
    {sec:"55", ch:"V", title:"Nomination", provision:"Employee with 1+ year service must nominate gratuity recipient; family nomination mandatory if family exists; fresh nomination mandatory after marriage; modification provisions.", app:"Gratuity"},
    {sec:"56", ch:"V", title:"Determination of amount of gratuity", provision:"FORM-IV application to employer; employer determines admissible amount within 30 days and issues FORM-V; disputes to Competent Authority; appeal provisions; Recovery via FORM-IX.", app:"Gratuity"},
    {sec:"57", ch:"V", title:"Compulsory insurance", provision:"Employers (except Govt) must insure gratuity liability with LIC or approved insurer; exemption for approved gratuity funds with 500+ employees or guaranteed by Govt.", app:"Gratuity"},
    {sec:"58", ch:"V", title:"Competent authority", provision:"Appropriate Govt appoints Competent Authority for gratuity implementation; qualifications and powers prescribed; appeals from Competent Authority lie to Appellate Authority.", app:"Gratuity"},

    // CHAPTER VI — MATERNITY BENEFIT (Sections 59-72)
    {sec:"59", ch:"VI", title:"Employment of women prohibited during certain period", provision:"No employment/work for 6 weeks immediately following delivery, miscarriage or MTP; no arduous work or work likely to interfere with pregnancy in last month on request.", app:"Maternity"},
    {sec:"60", ch:"VI", title:"Right to payment of maternity benefit", provision:"Average daily wage for actual period of absence; 80 days work in preceding 12 months mandatory; max 26 weeks (12 weeks if 2+ children); 8 weeks before expected delivery.", app:"Maternity"},
    {sec:"61", ch:"VI", title:"Continuance of payment in certain cases", provision:"Maternity benefit continues until ESI maternity benefit eligibility qualifies if Chapter IV applies to establishment; no double payment of both benefits.", app:"Maternity"},
    {sec:"62", ch:"VI", title:"Notice of claim and payment", provision:"Written notice with FORM-X to employer; advance payment on pregnancy proof; balance within 48 hours of delivery proof; payment to nominee if woman dies before receiving.", app:"Maternity"},
    {sec:"63", ch:"VI", title:"Payment in case of death of woman", provision:"Benefit payable to nominee/legal heir if woman dies; if both mother and child die, payment until day of death only.", app:"Maternity"},
    {sec:"64", ch:"VI", title:"Payment of medical bonus", provision:"₹3,500 medical bonus if employer does not provide free pre-natal and post-natal care; payable with last instalment of maternity benefit.", app:"Maternity"},
    {sec:"65", ch:"VI", title:"Leave for miscarriage, etc.", provision:"6 weeks paid leave for miscarriage/MTP; 2 weeks for tubectomy operation; 1 month for illness arising from pregnancy, delivery, premature birth or miscarriage.", app:"Maternity"},
    {sec:"66", ch:"VI", title:"Nursing breaks", provision:"Two nursing breaks of prescribed duration daily until child attains 15 months; in addition to regular rest intervals; cannot be deducted from wages.", app:"Maternity"},
    {sec:"67", ch:"VI", title:"Creche facility", provision:"Mandatory crèche for establishments with 50+ employees; children under 6 years; CCTV monitored; police-verified staff; 4 visits/day allowed; common facility option available.", app:"Maternity (50+ Employees)"},
    {sec:"68", ch:"VI", title:"Dismissal for absence during pregnancy", provision:"Unlawful to dismiss or discharge woman during or on account of maternity absence; woman may appeal to Competent Authority within 60 days.", app:"Maternity"},
    {sec:"69", ch:"VI", title:"No deduction of wages in certain cases", provision:"No wage deduction for light work assignment during pregnancy or for nursing breaks; no adverse entry in service record for these absences.", app:"Maternity"},
    {sec:"70", ch:"VI", title:"Forfeiture of maternity benefit", provision:"Benefit forfeited if woman works for remuneration during permitted maternity absence period; employer may deduct amount already paid.", app:"Maternity"},
    {sec:"71", ch:"VI", title:"Duties of employer", provision:"Display abstract of Chapter VI provisions in local language in FORM-XIV at every establishment where women are employed.", app:"Maternity"},
    {sec:"72", ch:"VI", title:"Power of Inspector-cum-Facilitator to direct payments", provision:"Inspector may order payment of withheld maternity benefits; complaint in FORM-XIII-A; appeal in FORM-XIII-B; appeal to prescribed authority within 30 days.", app:"Maternity"},

    // CHAPTER VII — EMPLOYEES' COMPENSATION (Sections 73-99)
    {sec:"73", ch:"VII", title:"Reports of fatal accidents and serious bodily injuries", provision:"Report to Competent Authority within 7 days of death or serious injury at workplace; State Govt may extend applicability to other premises.", app:"Compensation"},
    {sec:"74", ch:"VII", title:"Employer's liability for compensation", provision:"Liability for employment injury causing death, permanent/temporary total disablement, or permanent partial disablement; exceptions: injury <3 days, intoxication, wilful disobedience of safety rules.", app:"Compensation"},
    {sec:"75", ch:"VII", title:"Compensation in case of death or injury in plantation", provision:"Employer liable for death/injury from collapse of employer-provided housing in plantation; Housing Board or State Govt construction does not absolve employer.", app:"Compensation"},
    {sec:"76", ch:"VII", title:"Amount of compensation", provision:"Death: 50% monthly wages × relevant factor (Schedule V); Permanent total disablement: 60% × factor; Permanent partial: proportional; Temporary: 25% wages half-monthly; medical expenses reimbursed.", app:"Compensation"},
    {sec:"77", ch:"VII", title:"Compensation to be paid when due and damages for default", provision:"Immediate payment on liability accrual; provisional payment if liability disputed; interest at 12% and up to 50% damages for default in payment without justification.", app:"Compensation"},
    {sec:"78", ch:"VII", title:"Method of calculating monthly wages", provision:"12-month average if employed ≥12 months; locality average if employed <1 month; 30× daily wage otherwise; casual/seasonal workers: separate computation.", app:"Compensation"},
    {sec:"79", ch:"VII", title:"Review", provision:"Half-monthly payments reviewable on medical certificate or prescribed conditions; may be continued/increased/decreased/terminated.", app:"Compensation"},
    {sec:"80", ch:"VII", title:"Commutation of half-monthly payments", provision:"Lump sum redemption by agreement registered with Competent Authority or after 6 months of payments via Competent Authority determination.", app:"Compensation"},
    {sec:"81", ch:"VII", title:"Distribution of compensation", provision:"Death compensation deposited with Competent Authority; apportioned among dependants after inquiry; investment in approved securities for minors.", app:"Compensation"},
    {sec:"82", ch:"VII", title:"Notice and claim", provision:"Notice of accident required; claim within 2 years of accident or diagnosis; notice-book to be maintained; employer's knowledge substitutes for formal notice.", app:"Compensation"},
    {sec:"83", ch:"VII", title:"Special provisions for accidents outside India", provision:"Applies to ship masters/seamen, aircraft crew, Indians working abroad for Indian employers; service of claims on masters/captains/agents in India.", app:"Compensation"},
    {sec:"84", ch:"VII", title:"Medical examination", provision:"Employee must submit to employer-offered medical examination; refusal suspends compensation rights; employer cannot bar employee from engaging own doctor.", app:"Compensation"},
    {sec:"85", ch:"VII", title:"Contracting", provision:"Principal employer liable for contractor's employees; indemnity provisions between employer and contractor may be set off from compensation.", app:"Compensation"},
    {sec:"86", ch:"VII", title:"Remedies of employer against stranger", provision:"Employer who paid compensation may recover from third party legally liable for the injury causing the accident.", app:"Compensation"},
    {sec:"87", ch:"VII", title:"Insolvency of employer", provision:"Insurance rights transfer to employee on employer insolvency; compensation dues given priority in distribution of insolvent estate.", app:"Compensation"},
    {sec:"88", ch:"VII", title:"Power to require statements regarding fatal accidents", provision:"Competent Authority may require employer statement on fatal accident; dependants informed of their right to claim compensation.", app:"Compensation"},
    {sec:"89", ch:"VII", title:"Registration of agreements", provision:"Lump sum settlement agreements must be registered with Competent Authority; enforceable as decree despite Contract Act provisions.", app:"Compensation"},
    {sec:"90", ch:"VII", title:"Reference to competent authority", provision:"All disputes on liability, amount, duration and apportionment referred to Competent Authority; Civil Court jurisdiction barred on these matters.", app:"Compensation"},
    {sec:"91", ch:"VII", title:"Appointment of competent authority", provision:"State Govt appoints Competent Authority: 5+ years judicial service/5+ years as advocate/Gazetted officer with HR/legal experience.", app:"Compensation"},
    {sec:"92", ch:"VII", title:"Venue of proceedings and transfer", provision:"Proceedings at accident place/employee residence/employer office; transfer of proceedings between Competent Authorities with consent or on application.", app:"Compensation"},
    {sec:"93", ch:"VII", title:"Form of application", provision:"Claim application in FORM-XXVII with FORM-XXVIII certificate; prescribed fee; Competent Authority to dispose within prescribed time.", app:"Compensation"},
    {sec:"94", ch:"VII", title:"Power to require further deposit in fatal accident cases", provision:"Competent Authority may call for additional deposit from employer if initial compensation deposited appears insufficient for all dependants.", app:"Compensation"},
    {sec:"95", ch:"VII", title:"Powers and procedure of competent authority", provision:"Civil Court powers: evidence, summons, documents, commissions; deemed Civil Court for CrPC purposes; may record compromise settlements.", app:"Compensation"},
    {sec:"96", ch:"VII", title:"Appearance of parties", provision:"Representation by legal practitioner, insurance official, trade union officer, Inspector-cum-Facilitator, or other authorised person.", app:"Compensation"},
    {sec:"97", ch:"VII", title:"Method of recording evidence", provision:"Brief memorandum of all evidence; medical evidence recorded word-for-word; evidence open to inspection by parties.", app:"Compensation"},
    {sec:"98", ch:"VII", title:"Power to submit cases", provision:"Competent Authority may refer questions of law to High Court; High Court's opinion is binding on the Competent Authority.", app:"Compensation"},
    {sec:"99", ch:"VII", title:"Appeal against order of competent authority", provision:"Appeal to High Court only on substantial question of law; ₹10,000 minimum dispute amount for appeal; 60-day limitation from date of order.", app:"Compensation"},

    // CHAPTER VIII — BOCW (Sections 100-108)
    {sec:"100", ch:"VIII", title:"Levy and collection of cess", provision:"1-2% cess on cost of construction (excluding land cost and compensation paid under Land Acquisition Act); collected via local authority or advance payment before project start.", app:"BOCW"},
    {sec:"101", ch:"VIII", title:"Interest payable on delay in payment of cess", provision:"Interest at prescribed rate (Rule 42: 1% per month) on delayed cess payment from due date; compounded monthly on unpaid amount.", app:"BOCW"},
    {sec:"102", ch:"VIII", title:"Power to exempt from cess", provision:"Appropriate Govt may exempt if cess already levied under corresponding State law; no double levy on same construction work.", app:"BOCW"},
    {sec:"103", ch:"VIII", title:"Self-assessment of cess", provision:"Employer self-assesses cess in FORM-XVI certified by Chartered Engineer within 60 days of completion; Assessing Officer may reassess; self-assessment final if Officer fails within 180 days.", app:"BOCW"},
    {sec:"104", ch:"VIII", title:"Penalty for non-payment of cess", provision:"Penalty up to cess amount for non-payment within assessment order date; show-cause hearing required; interest continues from due date.", app:"BOCW"},
    {sec:"105", ch:"VIII", title:"Appeal to appellate authority", provision:"Appeal in FORM-XIX against assessment/penalty within 90 days; Appellate Authority decision final subject to High Court jurisdiction on law.", app:"BOCW"},
    {sec:"106", ch:"VIII", title:"Registration of building workers as beneficiaries", provision:"Building workers aged 18-60 with 90+ days work in preceding 12 months registered by BOCW Board; Aadhaar-based registration on portal; digital identity card issued.", app:"BOCW"},
    {sec:"107", ch:"VIII", title:"Cessation as a beneficiary", provision:"Registration ceases at age 60 or if <90 days work per year for 3 consecutive years; 3+ years continuous beneficiaries eligible for post-60 benefits.", app:"BOCW"},
    {sec:"108", ch:"VIII", title:"Building Workers' Welfare Fund and its applications", provision:"Fund credited with cess, grants, other sums; applied for welfare benefits, salaries, authorised expenses; administrative expenses capped at 5% of annual income.", app:"BOCW"},

    // CHAPTER IX — UNORGANISED/GIG/PLATFORM WORKERS (Sections 109-114)
    {sec:"109", ch:"IX", title:"Framing of schemes for unorganised workers", provision:"Central/State Govt may frame welfare schemes: life/disability insurance, health/maternity benefits, old age protection, education, housing; funding from Budget, CSR, grants.", app:"Unorganised"},
    {sec:"110", ch:"IX", title:"Funding of State Government schemes", provision:"State schemes funded by State Budget, worker contributions, CSR, other sources; Central financial assistance possible on meeting prescribed conditions.", app:"Unorganised"},
    {sec:"111", ch:"IX", title:"Record keeping", provision:"Scheme records maintained electronically with continuous numbering to avoid duplication; UAN-linked records for all registered unorganised/gig/platform workers.", app:"Unorganised/Gig/Platform"},
    {sec:"112", ch:"IX", title:"Helpline, facilitation centre for unorganised/gig/platform workers", provision:"Appropriate Govt may set up helplines and facilitation centres for information, registration assistance, and scheme enrolment for workers.", app:"Unorganised/Gig/Platform"},
    {sec:"113", ch:"IX", title:"Registration of unorganised/gig/platform workers", provision:"Registration for workers 16+ years via Aadhaar-based self-declaration on Central Government portal; UAN issued; digital identity card; aggregators share data via API within 45 days of Rules.", app:"Unorganised/Gig/Platform"},
    {sec:"114", ch:"IX", title:"Schemes for gig workers and platform workers", provision:"Central Govt may frame schemes: life/disability, accident, health/maternity, old age, crèche, education; aggregator contribution 1-2% of annual turnover or max 5% of amount paid to gig workers.", app:"Gig/Platform"},

    // CHAPTER X — FINANCE AND ACCOUNTS (Sections 115-121)
    {sec:"115", ch:"X", title:"Accounts", provision:"Each Social Security Organisation maintains proper accounts as specified by appropriate Govt after C&AG consultation; separate fund accounts mandated.", app:"All Organisations"},
    {sec:"116", ch:"X", title:"Audit", provision:"Annual audit by Comptroller and Auditor General; audit rights same as for Govt accounts; audit report forwarded to Parliament/State Legislature.", app:"All Organisations"},
    {sec:"117", ch:"X", title:"Budget estimates", provision:"Organisations submit annual budget showing probable receipts and expenditure for next year; Central/State Govt approval required for major expenditure items.", app:"All Organisations"},
    {sec:"118", ch:"X", title:"Annual report", provision:"Organisations submit annual report with adopted budget; placed before Parliament/State Legislature with C&AG audit report.", app:"All Organisations"},
    {sec:"119", ch:"X", title:"Valuation of assets and liabilities", provision:"Fund valuation by appointed valuer/actuary: Central Board annually, Corporation triennially, BOCW Boards as specified; actuarial valuation mandatory for pension fund.", app:"All Organisations"},
    {sec:"120", ch:"X", title:"Holding of property by Social Security Organisation", provision:"Organisations may acquire/hold/transfer property, invest funds in approved securities, raise loans, constitute benefit funds subject to prescribed conditions.", app:"All Organisations"},
    {sec:"121", ch:"X", title:"Writing off of losses", provision:"Organisations may write off irrecoverable dues with prescribed authority approval; scheme-specific provisions for EPF/Pension/Insurance Funds.", app:"All Organisations"},

    // CHAPTER XI — AUTHORITIES, ASSESSMENT, COMPLIANCE (Sections 122-132)
    {sec:"122", ch:"XI", title:"Appointment of Inspector-cum-Facilitators and their powers", provision:"Appointed by appropriate Govt; web-based inspection scheme with randomised selection; powers: examine persons, require documents, search/seize records, report defects, advise on compliance.", app:"All"},
    {sec:"123", ch:"XI", title:"Maintenance of records, registers, returns", provision:"Employer maintains: employee register (Wages Rules Form-I), attendance (Form-IX), wages/OT (Form-IV), women employees register (FORM-XXII), wage slips; annual return FORM-XXIII by 28/29 Feb; preserve 5 years.", app:"All Establishments"},
    {sec:"124", ch:"XI", title:"Employer not to reduce wages", provision:"Prohibition on reducing wages, benefits or service conditions due to Code-imposed contributions or compliance costs; any such reduction void and of no effect.", app:"All"},
    {sec:"125", ch:"XI", title:"Assessment and determination of dues from employer", provision:"Authorised Officers determine applicability and dues; inquiry concluded within 2 years; Civil Court powers for inquiry proceedings.", app:"EPF/ESI"},
    {sec:"126", ch:"XI", title:"Appeal against order of Authorised Officer relating to Chapter IV", provision:"Appeal to Appellate Authority (Joint Director level+) within 60 days; 25% deposit required; refund with 12% interest if appeal succeeds.", app:"ESI"},
    {sec:"127", ch:"XI", title:"Interest on amount due", provision:"Simple interest at notified rate on overdue amounts from due date to payment date; rate prescribed by Central Government periodically.", app:"All"},
    {sec:"128", ch:"XI", title:"Power to recover damages", provision:"Damages up to arrears amount for contribution default or other failure; show-cause hearing mandatory; waiver possible for resolved insolvency cases.", app:"EPF/ESI"},
    {sec:"129", ch:"XI", title:"Recovery of amount due", provision:"Recovery modes: attachment and sale of property, arrest and detention of defaulter, appointment of receiver; establishment property attached first.", app:"All"},
    {sec:"130", ch:"XI", title:"Validity of certificate and amendment", provision:"Certificate correctness not disputable before Recovery Officer; amendment for arithmetical errors; stay on appeal to appropriate authority.", app:"All"},
    {sec:"131", ch:"XI", title:"Other modes of recovery", provision:"Recovery from third parties holding employer money; notice to banks and insurers; court application for custody money; distraint under Income-tax Act procedures.", app:"All"},
    {sec:"132", ch:"XI", title:"Application of Income-tax Act provisions", provision:"Income-tax Act Second and Third Schedules and Certificate Proceedings Rules apply to Code recoveries with necessary modifications.", app:"All"},

    // CHAPTER XII — OFFENCES AND PENALTIES (Sections 133-138)
    {sec:"133", ch:"XII", title:"Penalty for failure to pay contributions, etc.", provision:"Non-payment of EPF/ESI contributions: 1-3 years imprisonment + fine; gratuity/compensation non-payment: 1 year + fine; other offences: fine up to ₹50,000.", app:"All"},
    {sec:"134", ch:"XII", title:"Enhanced punishment after previous conviction", provision:"Repeat offences: up to 2 years + ₹2 lakh fine; contribution/benefit non-payment repeats: 2-3 years + ₹3 lakh fine.", app:"All"},
    {sec:"135", ch:"XII", title:"Offences by companies", provision:"Company officers in charge liable; directors/secretaries liable if offence committed with their consent, connivance or gross negligence.", app:"All"},
    {sec:"136", ch:"XII", title:"Cognizance of offences", provision:"Complaint by notified Inspector-cum-Facilitator only; prior sanction required for prosecution; Metropolitan/Judicial Magistrate First Class tries offences.", app:"All"},
    {sec:"137", ch:"XII", title:"Prior opportunity before prosecution", provision:"Inspector-cum-Facilitator must give written direction for compliance before prosecution; no prior opportunity for repeat violations within 3 years.", app:"All"},
    {sec:"138", ch:"XII", title:"Compounding of offences", provision:"First-time offences punishable with fine only or ≤1 year + fine may be compounded: 50-75% of max fine in FORM-XXIV; no compounding for repeats within 3 years; amount credited to Social Security Fund.", app:"All"},

    // CHAPTER XIII — EMPLOYMENT INFORMATION (Sections 139-140)
    {sec:"139", ch:"XIII", title:"Reporting of vacancies to career centres", provision:"Employers report vacancies in FORM-XXV to career centres within 30 days before filling; unique vacancy ID issued within 3 working days; annual EIR in FORM-XXVI within 30 days of FY end.", app:"All Establishments"},
    {sec:"140", ch:"XIII", title:"Exclusions from application of this chapter", provision:"Exclusions: agriculture/domestic service/Parliament staff/employment <90 days/establishments with <20 employees/promotions/vacancies with low remuneration.", app:"Employment"},

    // CHAPTER XIV — MISCELLANEOUS (Sections 141-164)
    {sec:"141", ch:"XIV", title:"Social Security Fund", provision:"Central/State Social Security Funds for unorganised/gig/platform workers; sources include scheme funding, offence composition amounts, and transfers from other social security funds.", app:"Unorganised/Gig/Platform"},
    {sec:"142", ch:"XIV", title:"Application of Aadhaar", provision:"Aadhaar mandatory for registration, benefit claims, career centre services, payments; foreigners to obtain Aadhaar upon becoming resident of India.", app:"All"},
    {sec:"143", ch:"XIV", title:"Power to exempt establishment", provision:"Appropriate Govt may exempt establishments if substantially similar or superior benefits provided; conditions prescribed; 3-year initial exemption with review.", app:"All"},
    {sec:"144", ch:"XIV", title:"Power to defer or reduce", provision:"Central Govt may defer/reduce EPF/ESI contributions up to 3 months during pandemic/endemic/national disaster declaration.", app:"EPF/ESI"},
    {sec:"145", ch:"XIV", title:"Liability in case of transfer of establishment", provision:"Transferor and transferee jointly liable for pre-transfer dues; transferee liability limited to value of assets obtained in transfer.", app:"All"},
    {sec:"146", ch:"XIV", title:"Members, officers and staff to be public servants", provision:"All Code functionaries, members of Boards and Corporations deemed public servants under IPC Section 21.", app:"All"},
    {sec:"147", ch:"XIV", title:"Protection of action taken in good faith", provision:"No suit or prosecution against any person for anything done in good faith in pursuance of Code provisions.", app:"All"},
    {sec:"148", ch:"XIV", title:"Misuse of benefits", provision:"Appropriate Govt may deprive establishment/person of Code benefits for misuse after giving show-cause opportunity.", app:"All"},
    {sec:"149", ch:"XIV", title:"Power of Central Government to give directions", provision:"Central Govt may direct State Govts and Social Security Organisations on implementation of Code provisions.", app:"All"},
    {sec:"150", ch:"XIV", title:"Power to frame schemes", provision:"Appropriate Govt may frame schemes for Code implementation subject to previous publication of 45 days.", app:"All"},
    {sec:"151", ch:"XIV", title:"Protection against attachment", provision:"PF/ESI/gratuity/maternity/compensation amounts not assignable or attachable by court decree; priority under Insolvency Code.", app:"All"},
    {sec:"152", ch:"XIV", title:"Power to amend Schedule", provision:"Central Govt may amend Schedules I, IV-VII by notification; appropriate Govt may add to Schedules II-III; laid before Parliament for 30 days.", app:"All"},
    {sec:"153", ch:"XIV", title:"Transitional provisions", provision:"Existing organisations under repealed Acts continue functions until reconstituted under Code or until their prescribed terms expire; existing schemes continue.", app:"All"},
    {sec:"154", ch:"XIV", title:"Power of appropriate Government to make rules", provision:"Appropriate Govt may make rules for Code implementation on enumerated matters; published rules laid before legislature.", app:"All"},
    {sec:"155", ch:"XIV", title:"Power of Central Government to make rules", provision:"Central Govt makes rules for EPF, ESI, and other Code provisions; prior publication of 45 days required; laid before Parliament.", app:"All"},
    {sec:"156", ch:"XIV", title:"Power of State Government to make rules", provision:"State Govt makes rules for BOCW, unorganised workers, and other State-level provisions; laid before State Legislature.", app:"All"},
    {sec:"157", ch:"XIV", title:"Power of Corporation to make regulations", provision:"Corporation may make regulations for ESI administration including contributions, benefits, medical care, returns and penalties; Central Govt prior approval required.", app:"ESI"},
    {sec:"158", ch:"XIV", title:"Prior publication of rules, regulations, etc.", provision:"45-day previous publication requirement for rules/regulations/schemes; dispensable in epidemic/pandemic/disaster; objections considered before finalisation.", app:"All"},
    {sec:"159", ch:"XIV", title:"Rules for international compensation transfers", provision:"Rules for transferring compensation to/from foreign countries under bilateral agreements; consent of employer required for fatal accident transfers.", app:"Compensation"},
    {sec:"160", ch:"XIV", title:"Laying of rules, regulations and schemes", provision:"Central rules/regulations/schemes laid before Parliament; State rules/schemes laid before State Legislature; Parliament may modify or annul within 30-day period.", app:"All"},
    {sec:"161", ch:"XIV", title:"Effect of laws and agreements inconsistent with Code", provision:"Code prevails over inconsistent laws/awards/agreements; more favourable benefits under other instruments continue to apply to employees.", app:"All"},
    {sec:"162", ch:"XIV", title:"Delegation of powers", provision:"Appropriate Govt may delegate powers and functions to Social Security Organisations and subordinate officers with conditions.", app:"All"},
    {sec:"163", ch:"XIV", title:"Power to remove difficulties", provision:"Central Govt may make orders to remove implementation difficulties within 2 years of Code commencement; order laid before Parliament.", app:"All"},
    {sec:"164", ch:"XIV", title:"Repeal and savings", provision:"Repeals 9 earlier laws: EPF Act 1952, ESI Act 1948, Payment of Gratuity Act 1972, Maternity Benefit Act 1961, Employees Compensation Act 1923, BOCW Act 1996, BOCW Cess Act 1996, Unorganised Workers Social Security Act 2008, Cine Workers Welfare Fund Act 1981. All actions under repealed Acts deemed taken under Code.", app:"All"}
  ],

  // ============================================================
  // 69 CENTRAL RULES
  // ============================================================
  rules: [
    // Chapter I — Preliminary
    {r:"1",  ch:"I",    t:"Short title and commencement — SS (Central) Rules, 2026 effective 8 May 2026", c:"Preliminary", thresh:"All", codeRef:"Sec 1"},
    {r:"2",  ch:"I",    t:"Definitions — key terms: agency, benefit period, contribution period, standard benefit rate, gig worker, platform worker, UAN, etc.", c:"Preliminary", thresh:"All", codeRef:"Sec 2"},
    {r:"3",  ch:"I",    t:"Manner and conditions for making Chapter III or IV inapplicable — application on portal within 60 days; 5-year lock-in before exemption", c:"EPF", thresh:"EPF Establishments", codeRef:"Sec 1(5),(7)"},
    {r:"4",  ch:"I",    t:"Income of dependent parents of employee — threshold ₹14,000/month for ESI eligibility under Section 2(33)(e)", c:"ESI", thresh:"ESI Establishments", codeRef:"Sec 2(33)(e)"},
    {r:"5",  ch:"I",    t:"Registration of establishments and cancellation — common Form-I with OSH Rules on Shram Suvidha Portal; update within 30 days of any change", c:"Records", thresh:"All Establishments", codeRef:"Sec 3"},
    // Chapter II — Social Security Organisations
    {r:"6",  ch:"II",   t:"Administration of EPF funds — RBI/SBI/scheduled bank deposits; funds only for member benefits; prescribed investment norms", c:"EPF", thresh:"EPF", codeRef:"Sec 16(2)"},
    {r:"7",  ch:"II",   t:"Executive Committee of Central Board — composition, election procedure, casting vote of Chairperson, quorum of 5 members", c:"EPF", thresh:"EPF", codeRef:"Sec 4(3)"},
    {r:"8",  ch:"II",   t:"ESI Corporation, Standing Committee and Medical Benefit Committee — constitution, tenure, meetings, quorum, voting procedure", c:"ESI", thresh:"ESI", codeRef:"Sec 5(1),(3),(5)"},
    {r:"9",  ch:"II",   t:"National Social Security Board — member qualifications, term 5 years, meetings, quorum, agenda and proceedings", c:"Preliminary", thresh:"All", codeRef:"Sec 6(1)-(4)"},
    {r:"10", ch:"II",   t:"Other welfare measures and facilities — Central Government may specify additional benefits for unorganised/gig/platform workers", c:"Preliminary", thresh:"All", codeRef:"Sec 7(6)(j)"},
    {r:"11", ch:"II",   t:"Meetings, notice, list of business and quorum — 7-day notice; emergency meetings by Chairperson; prescribed voting procedure for Boards", c:"Preliminary", thresh:"All", codeRef:"Sec 9(1)"},
    {r:"12", ch:"II",   t:"Reconstitution of Corporation, Central Board, National Board — procedure on vacancy, expiry or supersession of organisation", c:"Preliminary", thresh:"All", codeRef:"Sec 11(1)"},
    // Chapter III — EPF Tribunal
    {r:"13", ch:"III",  t:"Form, manner, time limits and fees for EPF appeal — FORM-I; 60-day limit; language; ₹1,000 fee; affidavit required", c:"EPF", thresh:"EPF Disputants", codeRef:"Sec 23(2)"},
    // Chapter IV — ESI
    {r:"14", ch:"IV",   t:"Salary and allowances of Director General and Financial Commissioner — pay scales, house rent, transport, medical allowance", c:"ESI", thresh:"ESI", codeRef:"Sec 24(3)"},
    {r:"15", ch:"IV",   t:"Investment of ESI Fund — guidelines from Central Government; permissible instruments including Govt securities and bank FDs", c:"ESI", thresh:"ESI", codeRef:"Sec 25(4)"},
    {r:"16", ch:"IV",   t:"Limits for defraying expenditure on health promotion — must not exceed prescribed % of Corporation's revenue income", c:"ESI", thresh:"ESI", codeRef:"Sec 33"},
    {r:"17", ch:"IV",   t:"Holding of property by Corporation — may acquire/hold/transfer immovable property with Central Govt approval", c:"ESI", thresh:"ESI", codeRef:"Sec 27(1)"},
    {r:"18", ch:"IV",   t:"Insurance of employees — employer registers on ESIC portal on or before date of first employment; no grace period permitted", c:"ESI", thresh:"10+ Employees", codeRef:"Sec 28(1)"},
    {r:"19", ch:"IV",   t:"Rate of contributions — Employer: 3.25%; Employee: 0.75%; PwD employees: employer contribution waived up to 3 years from first contribution", c:"ESI", thresh:"10+ Employees", codeRef:"Sec 29(2)"},
    {r:"20", ch:"IV",   t:"Administrative expenses of Corporation — must not exceed 15% of total revenue income of Corporation in a financial year", c:"ESI", thresh:"ESI", codeRef:"Sec 30"},
    {r:"21", ch:"IV",   t:"Limit for funeral expenses — ₹20,000 as notified; payable to eldest surviving family member; claim within 3 months of death", c:"ESI", thresh:"ESI", codeRef:"Sec 32(1)(f)"},
    {r:"22", ch:"IV",   t:"Qualification for sickness benefit — 78 contribution days in corresponding period; benefit paid at 70% of standard benefit rate", c:"ESI", thresh:"Insured Persons", codeRef:"Sec 32(3)"},
    {r:"23", ch:"IV",   t:"Appeal to Medical Appeal Tribunal — procedure, limitation period, fees, form of filing; further appeal to EI Court possible", c:"ESI", thresh:"ESI", codeRef:"Sec 37(7)(a)(i)"},
    {r:"24", ch:"IV",   t:"Second appeal to Employees' Insurance Court — conditions, limitation, no further appeal on facts; only on substantial questions of law", c:"ESI", thresh:"ESI", codeRef:"Sec 37(7)(b)"},
    {r:"25", ch:"IV",   t:"Qualification for medical benefit — insured person and family entitled from date of insurance; contribution thresholds for continuation post-employment", c:"ESI", thresh:"Insured Persons", codeRef:"Sec 39(3)"},
    {r:"26", ch:"IV",   t:"ESI Society — State Government may establish for medical care administration; functions, funding, administration prescribed", c:"ESI", thresh:"ESI", codeRef:"Sec 40(5)-(6)"},
    {r:"27", ch:"IV",   t:"Capitalised value of benefit — method for computing lump sum equivalent of permanent disablement half-monthly benefit payments", c:"ESI", thresh:"ESI", codeRef:"Sec 42(1)"},
    {r:"28", ch:"IV",   t:"Terms and conditions for scheme for other beneficiaries using ESI hospitals — user charges, eligibility, exclusions prescribed", c:"ESI", thresh:"ESI", codeRef:"Sec 44"},
    {r:"29", ch:"IV",   t:"Proceedings before Employees' Insurance Court — summons, evidence, procedure, FORM-II filing requirements", c:"ESI", thresh:"ESI", codeRef:"Sec 50(2)"},
    {r:"30", ch:"IV",   t:"Administration of ESI Fund — separate accounts for sickness, maternity, disablement, dependants; cannot use for non-specified purposes", c:"ESI", thresh:"ESI", codeRef:"Sec 25(1),(3)"},
    // Chapter V — Gratuity
    {r:"31", ch:"V",    t:"Gratuity invested for benefit of minor nominee — term deposit with SBI or nationalised bank; interest accrues till minority ends", c:"Gratuity", thresh:"All Employers", codeRef:"Sec 53(1) proviso"},
    {r:"32", ch:"V",    t:"Nomination, fresh nomination and modification — FORM-III within 90 days of 1 year service; Aadhaar of nominee mandatory; employer verifies and returns duplicate", c:"Gratuity", thresh:"All Employers", codeRef:"Sec 55(1),(4),(5)"},
    {r:"33", ch:"V",    t:"Application for gratuity and dispute resolution — FORM-IV (30 days); employer FORM-V (15 days); dispute FORM-VI; summons FORM-VII; payment order FORM-VIII; recovery FORM-IX", c:"Gratuity", thresh:"All Employers", codeRef:"Sec 56(1),(2),(5)"},
    {r:"34", ch:"V",    t:"Qualifications of competent authority for gratuity — rank and experience requirements; powers of Civil Court conferred", c:"Gratuity", thresh:"All Employers", codeRef:"Sec 58(1)"},
    // Chapter VI — Maternity
    {r:"35", ch:"VI",   t:"Certificate and notice of claim for maternity benefit — FORM-X proof of pregnancy/delivery; FORM-XI notice; employer pays within 48 hours of FORM-X", c:"Maternity", thresh:"All Establishments", codeRef:"Sec 60, Sec 62"},
    {r:"36", ch:"VI",   t:"Duration of nursing breaks — 2 breaks of 15 minutes each + up to 15 minutes travel time to crèche facility each way", c:"Maternity", thresh:"All Establishments", codeRef:"Sec 66"},
    {r:"37", ch:"VI",   t:"Crèche facility — 50+ employees; CCTV monitored; police-verified staff; qualified personnel; children under 6; FORM-XII for dismissal appeal", c:"Maternity", thresh:"50+ Employees", codeRef:"Sec 67(1)"},
    {r:"38", ch:"VI",   t:"Gross misconduct — acts constituting gross misconduct for dismissal during maternity benefit period; employer must prove gross misconduct", c:"Maternity", thresh:"All Establishments", codeRef:"Sec 68(1) proviso 2"},
    {r:"39", ch:"VI",   t:"Complaint before Inspector-cum-Facilitator and appeal — FORM-XIII-A complaint; FORM-XIII-B appeal within 30 days of Inspector's order", c:"Maternity", thresh:"All Establishments", codeRef:"Sec 72(1),(3)"},
    {r:"40", ch:"VI",   t:"Duties of Inspector-cum-Facilitator — verify records, investigate complaints, display abstract in FORM-XIV at all establishments employing women", c:"Maternity", thresh:"All Establishments", codeRef:"Sec 122(5),(6)"},
    // Chapter VII — BOCW
    {r:"41", ch:"VII",  t:"Collection and refund of cess — FORM-XV before commencement; FORM-XVI self-assessment by Chartered Engineer; FORM-XVII stoppage; FORM-XVIII completion return within 60 days", c:"BOCW", thresh:"Construction Employers", codeRef:"Sec 100(2),(4), Sec 103(1)"},
    {r:"42", ch:"VII",  t:"Time limit and interest for cess — 1% per month interest on delayed cess payment from due date; no ceiling on total interest accrued", c:"BOCW", thresh:"Construction Employers", codeRef:"Sec 101"},
    {r:"43", ch:"VII",  t:"Penalty for non-payment of cess — Assessing Officer imposes penalty up to cess amount after show-cause hearing; appeal within 90 days", c:"BOCW", thresh:"Construction Employers", codeRef:"Sec 104"},
    {r:"44", ch:"VII",  t:"Appeal against cess assessment/penalty — FORM-XIX within 90 days to Appellate Authority; decision of Appellate Authority is final", c:"BOCW", thresh:"Construction Employers", codeRef:"Sec 105(1)"},
    {r:"45", ch:"VII",  t:"Registration of building worker — Aadhaar-based portal registration by employer/contractor; UAN and digital identity card issued; periodical update required", c:"BOCW", thresh:"Construction Employers", codeRef:"Sec 106"},
    {r:"46", ch:"VII",  t:"Benefits of BOCW beneficiary — minimum 3 years as beneficiary for eligibility for most welfare benefits; State Board specifies benefit rates", c:"BOCW", thresh:"BOCW Workers", codeRef:"Sec 107(2)"},
    {r:"47", ch:"VII",  t:"Recovery of cess dues and exemption — procedure for recovery of unpaid cess; exemption from cess if State law already levied equivalent cess", c:"BOCW", thresh:"Construction Employers", codeRef:"Sec 100(3), Sec 102"},
    // Chapter VIII — Gig/Platform Workers
    {r:"48", ch:"VIII", t:"Registration of unorganised/gig/platform workers — age 16+; Aadhaar-based; UAN issued; aggregators share worker data via API within 45 days of Rules; real-time daily exit data", c:"Gig/Platform", thresh:"All Aggregators", codeRef:"Sec 113(1),(2)"},
    {r:"49", ch:"VIII", t:"Implementation of schemes and refund — aggregator contribution to Social Security Fund; provisional FORM-XX by 30 June; final FORM-XXI by 31 October; refund within 90 days with 1% monthly interest", c:"Gig/Platform", thresh:"All Aggregators", codeRef:"Sec 114(4),(7)"},
    // Chapter IX — Finance
    {r:"50", ch:"IX",   t:"Conditions for acquiring property, investing, loans and benefit funds by Corporation/Central Board — prescribed norms and approval requirements", c:"Preliminary", thresh:"All", codeRef:"Sec 120(1)-(4)"},
    {r:"51", ch:"IX",   t:"Conditions for writing off irrecoverable dues — prescribed procedure with authority approval; separate thresholds for EPF, ESI, BOCW dues", c:"Preliminary", thresh:"All", codeRef:"Sec 121"},
    {r:"52", ch:"IX",   t:"Accounts and annual report — Corporation maintains complete accounts; audited annually by C&AG; annual report submitted to Central Government", c:"Records", thresh:"All", codeRef:"Sec 115,116,118"},
    // Chapter X — Records
    {r:"53", ch:"X",    t:"Form and manner for maintenance of records — Employee register (Wages Form-I); Attendance (Form-IX); Wages/OT (Form-IV); Women employees (FORM-XXII); preserve 5 years; annual return FORM-XXIII by 28/29 Feb", c:"Records", thresh:"All Establishments", codeRef:"Sec 123(1),(4)"},
    // Chapter XI — Offences
    {r:"54", ch:"XI",   t:"Compounding of offences — authorized officer issues FORM-XXIV notice (4 parts); compounding fee 50-75% of max; 15-day deposit deadline; Composition Certificate issued", c:"Preliminary", thresh:"All", codeRef:"Sec 138(1)"},
    // Chapter XII — Employment Exchange
    {r:"55", ch:"XII",  t:"Establishment and maintenance of career centre — Central/State Government; vacancy matching functions; designated authority for operations", c:"Preliminary", thresh:"All", codeRef:"Sec 2(9), Sec 139(1)"},
    {r:"56", ch:"XII",  t:"Reporting of vacancies and employment information return — FORM-XXV vacancy report within 30 days; FORM-XXVI annual EIR within 30 days of FY end; FORM-XXVI(A) job seeker registration", c:"Records", thresh:"All Establishments", codeRef:"Sec 139(1),(2)"},
    // Chapter XIII — Workers' Compensation
    {r:"57", ch:"XIII", t:"Rate of interest under section 77 — employer liable to pay interest on delayed compensation payment from date it became due", c:"Preliminary", thresh:"All Employers", codeRef:"Sec 77(3)(a)"},
    {r:"58", ch:"XIII", t:"Manner of notice and transmitting money under section 92 — application procedure for transfer; FORM-XXIX for transfer of compensation funds between jurisdictions", c:"Preliminary", thresh:"All", codeRef:"Sec 92(1),(3)"},
    {r:"59", ch:"XIII", t:"Form, manner and fee for compensation claim — FORM-XXVII application with FORM-XXVIII verification certificate; prescribed fee; time-limit for disposal", c:"Preliminary", thresh:"All", codeRef:"Sec 93(3)"},
    {r:"60", ch:"XIII", t:"Rules for international compensation transfers — bilateral arrangements with other countries; lump-sum transfer with employer consent for fatal accidents", c:"Preliminary", thresh:"All", codeRef:"Sec 159(1)"},
    {r:"62", ch:"XIII", t:"Transfer of records or money — FORM-XXX accident report with complete details forwarded when jurisdiction transfer is needed", c:"Preliminary", thresh:"All", codeRef:"Sec 92(3)"},
    // Chapter XIV — Exemptions and Social Security Fund
    {r:"64", ch:"XIV",  t:"Establishment and administration of Social Security Fund — gig/platform worker funds; separate accounts; Central Government administers", c:"Gig/Platform", thresh:"All", codeRef:"Sec 141(1)-(4)"},
    {r:"65", ch:"XIV",  t:"Eligibility conditions for EPF exemption — establishment must offer better PF benefits; all employees covered; no defaults; good track record for 3 years", c:"EPF", thresh:"EPF Establishments", codeRef:"Sec 143(1),(4)"},
    {r:"66", ch:"XIV",  t:"Time limit for Central Board/Corporation to provide views on exemption application — 60 days from receipt of complete application", c:"EPF", thresh:"EPF Establishments", codeRef:"Sec 143(1) proviso"},
    {r:"67", ch:"XIV",  t:"Terms and conditions for compliance of exempted establishment — annual returns to EPFO; actuarial audit; employee representation in trust", c:"EPF", thresh:"Exempted Establishments", codeRef:"Sec 143(2),(6)"},
    {r:"68", ch:"XIV",  t:"Terms and conditions for management of exempted PF trust — Board of Trustees constitution; equal employer-worker representation; investment norms per EPFO", c:"EPF", thresh:"Exempted Establishments", codeRef:"Sec 143(5)"},
    {r:"69", ch:"XIV",  t:"Manner of determining misuse of any benefit — investigation by Inspector; show cause; orders by Central Board/Corporation; recovery proceedings", c:"Preliminary", thresh:"All", codeRef:"Sec 148"}
  ],

  // ============================================================
  // 30 FORMS — FORM-I to FORM-XXX
  // ============================================================
  forms: [
    {n:"I",      ruleRef:"Rule 13(2)(a)",               cat:"EPF",                codeRef:"Sec 23",      cc:"#2E6FED", bg:"rgba(46,111,237,0.12)",  title:"Appeal to CGIT — Provident Fund",                                        desc:"Appeal under Section 23 to Central Government Industrial Tribunal against EPF assessment/damages order. Contains appeal index, appellant/respondent particulars, order details, jurisdiction declaration, facts, reliefs sought, and ₹1,000 bank draft details.", who:"EPF Disputants / Employers", deadline:"Within 60 days of order", filedBy:"Appellant", driveLink:"https://drive.google.com/file/d/1iM0jKx7PwntW6Zi8tTuGD-_qP599dNiD/view"},
    {n:"II",     ruleRef:"Rule 13(2)(c)",               cat:"EPF",                codeRef:"Sec 23",      cc:"#2E6FED", bg:"rgba(46,111,237,0.12)",  title:"Receipt Slip — EPF Appeal in CGIT",                                       desc:"Acknowledgement receipt issued by Registrar of CGIT on receipt of EPF appeal. Contains date of filing, date of receipt by post, registration number; issued with seal of Tribunal.", who:"Issued by Registrar, CGIT", deadline:"On receipt of appeal", filedBy:"Tribunal Registrar", driveLink:"https://drive.google.com/file/d/1mrOfVZrQ0DHi_VyiHxDlsnMSaLh2zJLx/view"},
    {n:"III",    ruleRef:"Rules 32(1),(2),(3),(4)",      cat:"Gratuity",           codeRef:"Sec 55",      cc:"#E8A020", bg:"rgba(232,160,32,0.12)",  title:"Nomination / Fresh Nomination / Modification for Gratuity",              desc:"Employee nominates, re-nominates or modifies gratuity nominee. Aadhaar of nominee mandatory. Employer verifies and returns attested duplicate within 30 days. Family nomination mandatory if family exists; nomination outside family void. Fresh nomination after marriage compulsory.", who:"All Employees", deadline:"Within 90 days of completing 1 year service", filedBy:"Employee → Employer", driveLink:"https://drive.google.com/file/d/1jFpu1gGWP41A0treVKw5vMEj4JrgRngI/view"},
    {n:"IV",     ruleRef:"Rule 33(1)",                  cat:"Gratuity",           codeRef:"Sec 56",      cc:"#E8A020", bg:"rgba(232,160,32,0.12)",  title:"Application for Payment of Gratuity",                                    desc:"Application to employer for gratuity on superannuation, retirement, resignation, total disablement, or death. Contains employee particulars, basis of claim, dates of appointment/termination, wages last drawn, total service period, and bank account details for payment.", who:"Employee / Nominee / Legal Heir", deadline:"Within 30 days from date gratuity became payable", filedBy:"Employee / Nominee / Legal Heir → Employer", driveLink:"https://drive.google.com/file/d/1WHN9uCSNeKdJpjb_3ZkRkmYsGnwV9Aas/view"},
    {n:"V",      ruleRef:"Rule 33(2)",                  cat:"Gratuity",           codeRef:"Sec 56",      cc:"#E8A020", bg:"rgba(232,160,32,0.12)",  title:"Notice for Payment / Rejection of Gratuity Claim",                       desc:"Employer either rejects claim with reasons or confirms admissible amount payable. Includes calculation: dates of appointment, termination, total service, wages last drawn, proportion payable. Copy sent to Competent Authority. Employer must pay within 30 days of determination.", who:"Employer → Employee / Nominee / Legal Heir", deadline:"Within 15 days of receiving FORM-IV", filedBy:"Employer", driveLink:"https://drive.google.com/file/d/1CnDWos52Evs0NKKLsrW8GqQ6Qe8zUqvt/view"},
    {n:"VI",     ruleRef:"Rule 33(4)",                  cat:"Gratuity",           codeRef:"Sec 56",      cc:"#E8A020", bg:"rgba(232,160,32,0.12)",  title:"Application for Direction — Gratuity Dispute",                           desc:"Filed before Competent Authority when employer refuses to pay gratuity, offers less than due, or disputes eligibility. Contains basis of claim, dispute particulars, full employee service record, wages, and amount claimed in Annexure.", who:"Employee / Nominee / Legal Heir → Competent Authority", deadline:"When employer fails to pay or disputes eligibility", filedBy:"Employee / Nominee / Legal Heir", driveLink:"https://drive.google.com/file/d/1U6B5e-w4vIPp3OScqIjsdq57LoFfPvSv/view"},
    {n:"VII",    ruleRef:"Rules 33(5),(8)",              cat:"Gratuity",           codeRef:"Sec 56",      cc:"#E8A020", bg:"rgba(232,160,32,0.12)",  title:"Notice / Summons — Competent Authority (Gratuity)",                      desc:"Issued by Competent Authority to employer or applicant to appear and answer material questions relating to gratuity application; also issued as summons for witnesses to produce documents. Ex-parte decision if absent without cause.", who:"Issued by Competent Authority", deadline:"As fixed by Competent Authority", filedBy:"Competent Authority → Employer / Witness", driveLink:"https://drive.google.com/file/d/1Cur37rXERO5_zh3D8OQE8d-WuQhLbK7C/view"},
    {n:"VIII",   ruleRef:"Rules 33(11),(12)(h)",         cat:"Gratuity",           codeRef:"Sec 56",      cc:"#E8A020", bg:"rgba(232,160,32,0.12)",  title:"Notice for Payment of Gratuity as Determined by Authority",              desc:"Direction by Competent or Appellate Authority to employer to pay determined gratuity amount within 30 days. Employer must intimate authority on payment. Copies sent to applicant and Appellate Authority as applicable.", who:"Issued by Competent Authority → Employer", deadline:"Employer must pay within 30 days of receipt", filedBy:"Competent / Appellate Authority", driveLink:"https://drive.google.com/file/d/1melj8NcjZghr_gnTcZlBGcYPolZnd2xV/view"},
    {n:"IX",     ruleRef:"Rule 33(13)",                 cat:"Gratuity",           codeRef:"Sec 56",      cc:"#E8A020", bg:"rgba(232,160,32,0.12)",  title:"Application for Recovery of Gratuity",                                   desc:"Filed before Competent Authority when employer fails to pay gratuity despite direction under Rule 33. Applicant prays for issue of recovery certificate under Section 129 of the Code.", who:"Employee / Nominee / Legal Heir → Competent Authority", deadline:"When employer fails to comply with FORM-VIII direction", filedBy:"Employee / Nominee / Legal Heir", driveLink:"https://drive.google.com/file/d/1D7oYSCxR5yzKN4zSfFaVetwxFQnqIRqW/view"},
    {n:"X",      ruleRef:"Rules 35(1)(a),(d),(2)(f)",    cat:"Maternity",          codeRef:"Sec 60,62",   cc:"#E858A8", bg:"rgba(232,88,168,0.12)",  title:"Medical Certificate — Pregnancy / Delivery / Miscarriage / MTP",         desc:"Certificate from Medical Officer, ASHA, ANM, Gram Pradhan, Village Administrative Officer, or Authorised Officer. Certifies pregnancy (with expected delivery date), actual delivery, miscarriage, MTP, tubectomy or pregnancy-related illness. Triggers employer's 48-hour payment obligation.", who:"Medical Authority → Employee → Employer", deadline:"As required; triggers 48-hour payment obligation", filedBy:"Medical Authority", driveLink:"https://drive.google.com/file/d/1zFrSYvBGd8LtPB2Kx35oozjVqOacyjgr/view"},
    {n:"XI",     ruleRef:"Rules 35(2)(a),(c)",           cat:"Maternity",          codeRef:"Sec 62",      cc:"#E858A8", bg:"rgba(232,88,168,0.12)",  title:"Notice of Claim for Maternity Benefit (Parts I & II)",                   desc:"PART I: Notice by woman employee stating expected confinement date, period of absence, and nominee for death benefit. PART II: Receipt acknowledging all amounts received including advance, installments, and ₹3,500 medical bonus.", who:"Woman Employee → Employer", deadline:"Notice before or as soon as possible after delivery", filedBy:"Woman Employee", driveLink:"https://drive.google.com/file/d/1QSaz0kOjqhwX6iyKYlenh_779gm_OsbK/view"},
    {n:"XII",    ruleRef:"Rule 38(2)",                   cat:"Maternity",          codeRef:"Sec 68",      cc:"#E858A8", bg:"rgba(232,88,168,0.12)",  title:"Appeal — Wrongful Deprivation of Maternity Benefit / Dismissal",         desc:"Appeal by woman employee before Competent Authority when wrongfully deprived of maternity benefit or medical bonus, or wrongfully discharged/dismissed during or on account of maternity absence. Attach copy of employer's order.", who:"Woman Employee / Nominee → Competent Authority", deadline:"Within 60 days of employer's deprivation/dismissal order", filedBy:"Woman Employee / Nominee", driveLink:"https://drive.google.com/file/d/1cQeY43sDIJDJ_9Mybh81paaqlmZ7P7C3/view"},
    {n:"XIII-A", ruleRef:"Rule 39(1)(a)",                cat:"Maternity",          codeRef:"Sec 72",      cc:"#E858A8", bg:"rgba(232,88,168,0.12)",  title:"Complaint to Inspector-cum-Facilitator — Maternity Benefit",             desc:"Complaint by woman employee, nominee or legal representative when maternity benefit, medical bonus or leave wages improperly withheld, or when wrongfully discharged/dismissed during maternity. Inspector must direct payment within prescribed time.", who:"Woman Employee / Nominee → Inspector-cum-Facilitator", deadline:"Any time during withholding of benefit", filedBy:"Woman Employee / Nominee / Legal Representative", driveLink:"https://drive.google.com/file/d/1LgVRkWRVyZuDRd2E-IsxQrWy5mGYtVim/view"},
    {n:"XIII-B", ruleRef:"Rule 39(2)(b)",                cat:"Maternity",          codeRef:"Sec 72",      cc:"#E858A8", bg:"rgba(232,88,168,0.12)",  title:"Appeal — Against Order of Inspector-cum-Facilitator (Maternity)",        desc:"Appeal by aggrieved woman employee or employer before Appellate Authority against order of Inspector-cum-Facilitator under Section 72 of the Code.", who:"Employee / Employer → Appellate Authority", deadline:"Within 30 days of Inspector's order", filedBy:"Aggrieved Party (Employee or Employer)", driveLink:"https://drive.google.com/file/d/16A7uj-ozckZ-rllqBu46ar8ezxTPr96s/view"},
    {n:"XIV",    ruleRef:"Rule 40(4)",                   cat:"Maternity",          codeRef:"Sec 71",      cc:"#E858A8", bg:"rgba(232,88,168,0.12)",  title:"Abstract of Maternity Benefit — Display at Establishment",               desc:"Statutory abstract of all key maternity benefit provisions under SS Code 2020. Must be prominently displayed at every establishment where women are employed. Inspector-cum-Facilitator verifies during all inspections. Non-display attracts penalty.", who:"Displayed at all establishments employing women", deadline:"Permanent display required at all times", filedBy:"Employer (for display)", driveLink:"https://drive.google.com/file/d/1gcB-kb5A0WXLWXlVcZlXsrneaTNJXDGH/view"},
    {n:"XV",     ruleRef:"Rules 41(1)(a),(b)",           cat:"BOCW",               codeRef:"Sec 100,103", cc:"#F07832", bg:"rgba(240,120,50,0.12)",  title:"Information for Commencement / Modification of Construction Work",        desc:"Intimation before commencing or modifying building or other construction work. Contains establishment details, construction site location, nature of work, date of commencement, approximate duration, and details of any modifications planned.", who:"Construction Employers / Contractors → Assessing Officer", deadline:"Before commencement of construction work", filedBy:"Employer / Contractor", driveLink:"https://drive.google.com/file/d/1A1QufQbZ2qB2U88cOLCcSjMaG_nmx2nT/view"},
    {n:"XVI",    ruleRef:"Rule 41(2)(b)",                cat:"BOCW",               codeRef:"Sec 103",     cc:"#F07832", bg:"rgba(240,120,50,0.12)",  title:"Self-Assessment of BOCW Cess for Construction Work",                     desc:"Self-assessment of BOCW cess certified by Chartered Engineer. Based on PWD/CPWD/RERA rates; provisional cess % as notified; yearly cess breakup for multi-year projects. SELF-ASSESSMENT IS FINAL if Assessing Officer fails to complete assessment within 180 days.", who:"Construction Employers / Contractors → Assessing Officer", deadline:"Before commencement; final after project completion", filedBy:"Employer (certified by Chartered Engineer)", driveLink:"https://drive.google.com/file/d/1ISXIOUtDp3NReVLtTu5Bk5ldxpEZvIQo/view"},
    {n:"XVII",   ruleRef:"Rules 41(2)(e),(5)(a),(b),(c)", cat:"BOCW",              codeRef:"Sec 103",     cc:"#F07832", bg:"rgba(240,120,50,0.12)",  title:"Notice for Stoppage / Reduction of Construction Work",                   desc:"Filed when construction work stops or is reduced. Contains total estimated cost, incurred cost up to stoppage, cess payable on incurred cost, cess already paid year-wise, outstanding or overpaid cess, and bank account details for refund if overpaid.", who:"Construction Employers / Contractors → Assessing Officer", deadline:"On stoppage or reduction of construction work", filedBy:"Employer (certified by Chartered Engineer)", driveLink:"https://drive.google.com/file/d/1mH2nwNwGkdjUIk3Mwu2foZ7v63g6kH6x/view"},
    {n:"XVIII",  ruleRef:"Rules 41(2)(f),(4)(a),(c),(e)", cat:"BOCW",              codeRef:"Sec 103",     cc:"#F07832", bg:"rgba(240,120,50,0.12)",  title:"Completion Return — Building or Other Construction Work",                 desc:"Return on completion of construction. Final reconciliation of cess based on actual incurred cost certified by Chartered Engineer. Contains total area, estimated vs actual cost, cess payable vs paid, outstanding/overpaid, bank account for refund.", who:"Construction Employers / Contractors → Assessing Officer", deadline:"Within 60 days of project completion", filedBy:"Employer (certified by Chartered Engineer)", driveLink:"https://drive.google.com/file/d/16-AZ_l7mSNDxZn6lIZTa6drLU-90ZaG_/view"},
    {n:"XIX",    ruleRef:"Rule 44(1)",                   cat:"BOCW",               codeRef:"Sec 105",     cc:"#F07832", bg:"rgba(240,120,50,0.12)",  title:"Appeal against BOCW Cess Assessment / Penalty Order",                    desc:"Employer appeals before Appellate Authority against (a) cess assessment order or (b) penalty order for non-payment/underpayment of cess. Contains establishment details, cess paid vs assessed, penalty amount imposed, and grounds for appeal with supporting documents.", who:"Construction Employers → Appellate Authority", deadline:"Within 90 days of assessment/penalty order", filedBy:"Employer", driveLink:"https://drive.google.com/file/d/1v-jXTX7CIFXFGs9ETcPBFj0KzwTUYXFJ/view"},
    {n:"XX",     ruleRef:"Rule 49(3)(a)",                cat:"Gig/Platform",       codeRef:"Sec 114",     cc:"#1ECDE8", bg:"rgba(30,205,232,0.10)",  title:"Provisional Self-Assessment by Aggregators — Gig / Platform Workers",    desc:"Provisional self-assessment and payment by aggregators for preceding financial year. Two assessment bases: (a) % of annual turnover as notified under Sec 114(4), or (b) 5% of amount paid to gig/platform workers. Contains aggregator details, worker count, turnover, and provisional contribution amount.", who:"All Aggregators → Central Government Portal", deadline:"By 30th June each year", filedBy:"Aggregator", driveLink:"https://drive.google.com/file/d/1ifrcqef_rMH6kohvCihy1zmBQ3IMznWE/view"},
    {n:"XXI",    ruleRef:"Rules 49(3)(b),(c)",           cat:"Gig/Platform",       codeRef:"Sec 114",     cc:"#1ECDE8", bg:"rgba(30,205,232,0.10)",  title:"Final Return and Refund Claim by Aggregators — Gig / Platform Workers",  desc:"Final return based on audited accounts; reconciles provisional payment (FORM-XX) against final contribution liability. Contains outstanding contribution payable or excess paid; bank account details for refund. Government pays 1% per month interest on delayed refund.", who:"All Aggregators → Central Government", deadline:"By 31st October each year", filedBy:"Aggregator", driveLink:"https://drive.google.com/file/d/1JhJbuKNCLcUQJNu5qo1XA_C0kC09i_-X/view"},
    {n:"XXII",   ruleRef:"Rule 53(1)(a)",                cat:"Records",            codeRef:"Sec 123",     cc:"#2ECC9A", bg:"rgba(46,204,154,0.10)",  title:"Register of Women Employees",                                            desc:"Mandatory register for every employer employing women. Month-wise tracking of days employed, laid off, and not employed. Records all maternity events, advances paid, medical bonus paid, and nominee details. Must be maintained at all times and available for inspection during working hours.", who:"All Employers employing women", deadline:"Maintained at all times; available for inspection", filedBy:"Employer (maintained)", driveLink:"https://drive.google.com/file/d/1eBizRmR6_-jTas1IfiYgpuHUOL_1--Aa/view"},
    {n:"XXIII",  ruleRef:"Rule 53(5)",                   cat:"Records",            codeRef:"Sec 123",     cc:"#2ECC9A", bg:"rgba(46,204,154,0.10)",  title:"Unified Annual Return — Gratuity, Maternity, IR, Safety (FORM-XXIII)",  desc:"Single integrated annual return filed online on MoLE web portal covering SS Code 2020, Code on Wages 2019, IR Code 2020, and OSH&WC Code 2020. PART-I for all establishments; PART-II for Mines only. Covers: gratuity, maternity, crèche, women employment, IR data, accidents, bonus, BOCW data.", who:"All Employers (Part-I); Mine Owners (Part-II)", deadline:"On or before 28th/29th February each year", filedBy:"Employer → MoLE Web Portal (Online)", driveLink:"https://drive.google.com/file/d/1AynAQH0hi52VPNzu4hFDekr3pVfJ1QkM/view"},
    {n:"XXIV",   ruleRef:"Rules 54(1),(2),(3)",          cat:"Compliance",         codeRef:"Sec 138",     cc:"#9B72E8", bg:"rgba(155,114,232,0.10)",  title:"Compounding Notice — Offences under the Code (Parts I, II, III, IV)",    desc:"Four-part form. PART-I: Notice by authorized officer. PART-II: Employer has 15 days to pay compounding fee. PART-III: Application by employer confirming payment. PART-IV: Composition Certificate certifying offence compounded. First-time offences only; amount credited to Social Security Fund.", who:"Authorized Officer → Employer (Notice); Employer → Officer (Application)", deadline:"Employer to pay within 15 days of notice", filedBy:"Authorized Officer (Notice & Certificate); Employer (Application)", driveLink:"https://drive.google.com/file/d/1ScihIx_jQcWwwM2tO46qZJr8EUmRBQkx/view"},
    {n:"XXV",    ruleRef:"Rules 56(1)(d),(3)(b)",        cat:"Employment",         codeRef:"Sec 139",     cc:"#60A5FA", bg:"rgba(96,165,250,0.10)",  title:"Form for Reporting Vacancies to Career Centres",                         desc:"Employer reports vacancies within 30 days; separate form per post type. Career Centre assigns unique vacancy ID within 3 working days. Contains employer details, vacancy designation, qualifications, age limits, pay scale, reservation obligations (SC/ST/OBC/EWS/PwD/Ex-serviceman).", who:"All Employers → Career Centre", deadline:"Within 30 days of vacancy arising", filedBy:"Employer", driveLink:"https://drive.google.com/file/d/1v9o7uB6CAKP9bIvKI29BEa89HSTSOKHk/view"},
    {n:"XXVI",   ruleRef:"Rules 56(1)(d),(6)",           cat:"Employment",         codeRef:"Sec 139",     cc:"#60A5FA", bg:"rgba(96,165,250,0.10)",  title:"Form EIR — Annual Employment Information Return",                        desc:"Annual employment information return to Career Centre (Regional) within 30 days after end of financial year. Covers: total manpower by skill category and gender, vacancies occurred/reported/filled, skill shortages, and next year estimated manpower requirements by occupation.", who:"All Establishments → Career Centre (Regional)", deadline:"Within 30 days after end of financial year", filedBy:"Employer", driveLink:"https://drive.google.com/file/d/1LnnIt-uO7IMO7JaXYO5__dj5mCIrOctW/view"},
    {n:"XXVII",  ruleRef:"Rule 59(1)",                   cat:"Workers Compensation",codeRef:"Sec 93",     cc:"#F87171", bg:"rgba(248,113,113,0.10)",  title:"Application for Compensation — Workers' Compensation",                   desc:"Filed before Competent Authority by injured employee or dependant. Contains accident details (date, cause, injuries sustained), monthly wages, age of applicant, notice of accident details, compensation claimed (half-monthly or lump sum), and specific questions in dispute.", who:"Injured Employee / Dependant → Competent Authority", deadline:"Within 2 years of accident; notice within 6 months", filedBy:"Injured Employee / Dependant", driveLink:"https://drive.google.com/file/d/12gtyfGKMLri2IBN9VdfqfxO4BKczGY-7/view"},
    {n:"XXVIII", ruleRef:"Rule 59(2)",                   cat:"Workers Compensation",codeRef:"Sec 93",     cc:"#F87171", bg:"rgba(248,113,113,0.10)",  title:"Certificate by Applicant — Workers' Compensation",                       desc:"Verification certificate accompanying FORM-XXVII. Applicant declares all particulars in FORM-XXVII are true to best of knowledge and belief, and that nothing has been concealed or misrepresented.", who:"Injured Employee / Dependant → Competent Authority", deadline:"Submitted along with FORM-XXVII", filedBy:"Applicant (accompanies FORM-XXVII)", driveLink:"https://drive.google.com/file/d/1quTq6jBid5uZd6lmc821SVoujeivo_Qq/view"},
    {n:"XXIX",   ruleRef:"Rule 58(1)",                   cat:"Workers Compensation",codeRef:"Sec 92",     cc:"#F87171", bg:"rgba(248,113,113,0.10)",  title:"Notice for Transfer / Settlement of Compensation Claim",                 desc:"Notice issued by Competent Authority to another Competent Authority informing that a claim for compensation has been made and the undersigned proposes to settle it; used for cross-jurisdiction transfer of compensation proceedings under Section 92.", who:"Competent Authority → Another Competent Authority / Government", deadline:"As required for settlement", filedBy:"Competent Authority", driveLink:"https://drive.google.com/file/d/12SwEJyrJlltgPRoYmsig_GjOd0Iryg9G/view"},
    {n:"XXX",    ruleRef:"Rule 62(1)",                   cat:"Workers Compensation",codeRef:"Sec 92",     cc:"#F87171", bg:"rgba(248,113,113,0.10)",  title:"Report on Accident — Transfer of Records / Compensation",                desc:"Detailed accident report furnished when workers' compensation matter needs processing in different jurisdiction. Complete details of deceased/disabled employee, circumstances of accident, compensation deposited by employer, list of original documents forwarded.", who:"Competent Authority → Another Competent Authority", deadline:"On transfer of jurisdiction", filedBy:"Competent Authority", driveLink:"https://drive.google.com/file/d/15lUP5QY4gIMhABTFoCr3E87_Pk8rHg9e/view"}
  ],

  // ============================================================
  // EMPLOYER SECTIONS — 10 Compliance Areas (A–J)
  // ============================================================
  employerSections: [
    {
      icon:"📝", title:"A. Registration & ESI Enrolment (Chapters I & IV)", color:"rgba(155,114,232,0.12)",
      items:[
        {rule:"Rule 5",  title:"Registration on Shram Suvidha Portal",             cls:"reg", codeRef:"Sec 3",       desc:"Common Form-I (OSH Rules) on Shram Suvidha Portal. Certificate automatic. Update within 30 days of any change. On closure: intimate within 30 days with proof of all dues paid. No separate SS registration needed — common with OSH Rules.", thresh:"All Establishments", forms:[]},
        {rule:"Rule 18", title:"ESI Employee Registration — Before First Employment", cls:"esi", codeRef:"Sec 28(1)", desc:"Register employees for ESI on ESIC portal on or before first day of employment. NO grace period permitted. Failure makes employer liable for full benefit cost + interest + penalty. New employees: register immediately before deployment.", thresh:"10+ Employees (ESI-covered)", forms:[]},
        {rule:"Rule 19", title:"ESI Contributions — 3.25% + 0.75%",                cls:"esi", codeRef:"Sec 29(2)",   desc:"EMPLOYER: 3.25% of wages. EMPLOYEE: 0.75% of wages. Both rounded to next higher rupee. PwD EXCEPTION: Employer's share WAIVED for up to 3 years from date of first contribution; Central Government reimburses ESIC. Contribution period: 6 months (Apr-Sep; Oct-Mar).", thresh:"10+ Employees", forms:[]}
      ]
    },
    {
      icon:"🏆", title:"B. Gratuity (Chapter V — Forms III to IX)", color:"rgba(232,160,32,0.12)",
      items:[
        {rule:"Rule 32", title:"Gratuity Nomination — FORM-III within 90 Days",    cls:"grt", codeRef:"Sec 55",     desc:"FORM-III within 90 days of completing 1 year service. Existing employees (pre-Rules): within 90 days of Rules commencement. Aadhaar of nominee mandatory. Family nomination mandatory if family exists; nomination outside family void. Employer verifies and returns attested duplicate within 30 days.", thresh:"All Employers", forms:["III"]},
        {rule:"Rule 33", title:"Gratuity Application & Payment — FORM-IV/V",       cls:"grt", codeRef:"Sec 56",     desc:"Employee files FORM-IV within 30 days. Employer: acknowledge, verify within 15 days, issue FORM-V of admissibility/rejection. FIXED-TERM EMPLOYEES: eligible if 1 year service completed. Disputes: FORM-VI before Competent Authority. Summons FORM-VII. Payment order FORM-VIII. Recovery: FORM-IX.", thresh:"All Employers", forms:["IV","V"]},
        {rule:"Rule 21", title:"ESI Funeral Expenses — ₹20,000",                   cls:"esi", codeRef:"Sec 32(1)(f)", desc:"₹20,000 payable on death of insured person. Payable to eldest surviving family member or person who performs last rites. Claim must be submitted within 3 months of death. Employer must report death to ESIC immediately.", thresh:"All ESI-covered Employees", forms:[]}
      ]
    },
    {
      icon:"🤱", title:"C. Maternity Benefit (Chapter VI — Forms X-XIV)", color:"rgba(232,88,168,0.12)",
      items:[
        {rule:"Rule 35",    title:"Maternity Claim — FORM-X + FORM-XI (48 Hours)",  cls:"mat", codeRef:"Sec 60,62", desc:"PROOF: FORM-X from doctor/ASHA/ANM/gram panchayat/municipality officer. NOTICE: FORM-XI (Part I — notice stating expected delivery date; Part II — receipt of all payments). PAYMENT: within 48 HOURS of FORM-X production. MEDICAL BONUS: ₹3,500 paid with maternity benefit if no free natal care.", thresh:"All Establishments", forms:["X","XI"]},
        {rule:"Rules 36-37", title:"Nursing Breaks + Crèche (50+ Employees)",        cls:"mat", codeRef:"Sec 66,67", desc:"NURSING BREAKS: 2 × 15 min + up to 15 min travel time to crèche. CRÈCHE (50+ employees): CCTV monitored during all working hours; police-verified staff; children under 6; no child left alone at any point; feeding room; evacuation plan displayed.", thresh:"All Establishments (Crèche: 50+)", forms:[]},
        {rule:"Rule 40",    title:"Display Abstract — FORM-XIV Permanent Display",   cls:"mat", codeRef:"Sec 71",    desc:"FORM-XIV abstract of all maternity benefit provisions must be prominently displayed at EVERY establishment where women are employed. Inspector-cum-Facilitator verifies during all inspections. Non-display: penalty up to ₹50,000.", thresh:"All Establishments employing women", forms:["XIV"]}
      ]
    },
    {
      icon:"🏗️", title:"D. BOCW Cess (Chapter VIII — Forms XV-XIX)", color:"rgba(240,120,50,0.12)",
      items:[
        {rule:"Rule 41",  title:"BOCW Cess — Self-Assessment Cycle (4 Forms)",      cls:"bocw", codeRef:"Sec 100,103", desc:"BEFORE COMMENCEMENT: File FORM-XV (intimation). Self-assess in FORM-XVI certified by Chartered Engineer at PWD/CPWD rates. Pay advance cess. ON STOPPAGE: File FORM-XVII. ON COMPLETION: File FORM-XVIII within 60 days. SELF-ASSESSMENT IS FINAL if Assessing Officer fails to complete assessment within 180 days.", thresh:"All Construction Employers", forms:["XV","XVI","XVII","XVIII"]},
        {rule:"Rules 42-44", title:"Cess Interest (1%/Month), Penalty & Appeal",   cls:"bocw", codeRef:"Sec 101,104,105", desc:"INTEREST: 1% PER MONTH on delayed cess payment from due date onwards — no ceiling on total interest. PENALTY: Assessing Officer imposes penalty up to cess amount for non-payment after show-cause hearing. APPEAL: FORM-XIX within 90 days to Appellate Authority.", thresh:"Construction Employers", forms:["XIX"]}
      ]
    },
    {
      icon:"📱", title:"E. Gig & Platform Workers (Chapter IX — Forms XX-XXI)", color:"rgba(10,127,160,0.12)",
      items:[
        {rule:"Rule 48", title:"Gig Worker Registration — API Within 45 Days",      cls:"gig", codeRef:"Sec 113", desc:"Workers 16+ register on Central Govt portal via Aadhaar; UAN and digital identity card issued. AGGREGATOR OBLIGATIONS: (1) Share EXISTING worker details via API within 45 DAYS of Rules commencement (DEADLINE: 22 Jun 2026). (2) Register NEW workers in real-time or daily. (3) Share exit details daily. UAN portable across platforms.", thresh:"All Aggregators", forms:[]},
        {rule:"Rule 49", title:"Aggregator Contribution & Returns — FORM-XX + XXI", cls:"gig", codeRef:"Sec 114", desc:"CONTRIBUTION: Up to 5% of amount paid to gig workers (% notified by Central Govt). PROVISIONAL RETURN: FORM-XX by 30 JUNE each year. FINAL RETURN: FORM-XXI by 31 OCTOBER (based on audited accounts). REFUND of excess within 90 days. 1% per month INTEREST on delayed refund from Govt.", thresh:"All Aggregators", forms:["XX","XXI"]}
      ]
    },
    {
      icon:"📁", title:"F. Records & Annual Return (Chapter XI — Forms XXII-XXIII)", color:"rgba(46,204,154,0.12)",
      items:[
        {rule:"Rule 53",    title:"4 Mandatory Registers + FORM-XXII (Women)",       cls:"rec", codeRef:"Sec 123",      desc:"Maintain: (1) Employee register — Wages Rules Form-I; (2) Attendance — Form-IX; (3) Wages/OT/Deductions — Form-IV; (4) Women employees — SS Rules FORM-XXII. All in English/Hindi/local language. PRESERVED 5 CALENDAR YEARS from last entry. Wage slips issued electronically on or before payment. Produced on demand before Inspector.", thresh:"All Establishments", forms:["XXII"]},
        {rule:"Rule 53(5)", title:"Annual Return — FORM-XXIII by 28/29 Feb Online",  cls:"rec", codeRef:"Sec 123(4)",    desc:"UNIFIED ANNUAL RETURN in FORM-XXIII uploaded online on MoLE portal on or before 28/29 FEBRUARY every year. Covers: gratuity, maternity, crèche, women employment, IR data, accidents, bonus, BOCW. INTEGRATED with OSH Code, IR Code, Code on Wages — one return covers all four Codes.", thresh:"All Establishments", forms:["XXIII"]}
      ]
    },
    {
      icon:"💼", title:"G. Employment Information & Career Centres (Forms XXV-XXVI)", color:"rgba(96,165,250,0.10)",
      items:[
        {rule:"Rule 56", title:"Vacancy Reporting & Annual Employment Return",       cls:"rec", codeRef:"Sec 139", desc:"Report vacancies in FORM-XXV to Career Centre within 30 days; separate form per post type. Career Centre issues unique vacancy ID within 3 working days. Annual Employment Information Return in FORM-XXVI to Career Centre (Regional) within 30 days of FY end — manpower, vacancies, skill shortages, next-year requirements.", thresh:"All Establishments", forms:["XXV","XXVI"]}
      ]
    },
    {
      icon:"⚖️", title:"H. Workers' Compensation (Chapter VII — Forms XXVII-XXX)", color:"rgba(248,113,113,0.10)",
      items:[
        {rule:"Rules 57-62", title:"Compensation Claims, Interest & Transfer",       cls:"reg", codeRef:"Sec 77,92,93", desc:"CLAIM: FORM-XXVII (application) with FORM-XXVIII (verification certificate) before Competent Authority. DELAYED COMPENSATION: Employer pays interest (Rule 57). TRANSFER: FORM-XXIX (notice for cross-jurisdiction transfer). ACCIDENT REPORT: FORM-XXX (detailed report for jurisdiction transfer). International: lump-sum transfers under bilateral agreements.", thresh:"All Employers", forms:["XXVII","XXVIII","XXIX","XXX"]}
      ]
    },
    {
      icon:"🔨", title:"I. Compounding of Offences (Chapter XI — Form XXIV)", color:"rgba(155,114,232,0.10)",
      items:[
        {rule:"Rule 54", title:"Compounding Notice — FORM-XXIV (4 Parts)",          cls:"reg", codeRef:"Sec 138", desc:"First-time offences under Code/Schemes/Rules/Regulations may be compounded. FORM-XXIV 4-part form. AMOUNT: 50-75% of maximum fine/penalty. DEADLINE: 15 days for employer to pay. COMPOSITION CERTIFICATE issued on payment. No further prosecution for compounded offence. Amount credited to Social Security Fund. No compounding for repeat within 3 years.", thresh:"All Establishments", forms:["XXIV"]}
      ]
    },
    {
      icon:"🏠", title:"J. EPF Exempted Establishments (Chapter XIV)", color:"rgba(29,78,216,0.10)",
      items:[
        {rule:"Rules 65-68", title:"Conditions for EPF Exemption & Trust Management", cls:"epf", codeRef:"Sec 143", desc:"Establishment must: offer better PF benefits than Code provisions; cover all employees; have no defaults in last 3 years; maintain good track record. Central Board gives views within 60 days. Annual returns to EPFO; actuarial audit; worker representation in trust; investment norms as per EPFO guidelines.", thresh:"Establishments Seeking EPF Exemption", forms:[]}
      ]
    }
  ],

  // ============================================================
  // CALENDAR EVENTS
  // ============================================================
  calEvents: [
    {title:"SS Rules 2026 — Effective Date",                   date:"20260508", desc:"G.S.R. 344(E) — SS (Central) Rules 2026 (69 Rules, 30 Forms) came into force on 8 May 2026.", id:"ss1"},
    {title:"⚠️ Aggregator API Data Sharing Deadline (Rule 48)", date:"20260622", desc:"All aggregators must share existing gig and platform worker details via API within 45 days of Rules commencement. Non-compliance attracts penal action.", id:"ss2"},
    {title:"Aggregator Provisional FORM-XX (Rule 49)",          date:"20260630", desc:"Every aggregator to self-assess and pay provisional gig/platform worker contribution in FORM-XX for preceding financial year.", id:"ss3"},
    {title:"Aggregator Final FORM-XXI (Rule 49)",               date:"20261031", desc:"Final aggregator return with audited contribution details. Excess refunded within 90 days with 1% monthly interest from Govt.", id:"ss4"},
    {title:"Annual Return FORM-XXIII (Rule 53) Due",            date:"20270228", desc:"Unified Annual Return (Gratuity + Maternity + IR + Safety) for 2026 filed online on MoLE web portal.", id:"ss5"}
  ],

  // ============================================================
  // TIMELINE
  // ============================================================
  timeline: [
    {date:"1948–2008", title:"Nine Earlier Social Security Laws",              sub:"ESI Act 1948, EPF Act 1952, Gratuity Act 1972, Maternity Benefit Act 1961, Employees Compensation Act 1923, BOCW Acts 1996, Unorganised Workers Act 2008, Cine Workers Act 1981 — all consolidated into single Code.", color:"#9B72E8"},
    {date:"28 Sep 2020", title:"Code on Social Security, 2020 Enacted",       sub:"Act No. 36 of 2020 — consolidates 9 earlier social security laws. 164 sections across 14 Chapters. First recognition of gig/platform workers in Indian labour law.", color:"#2ECC9A"},
    {date:"30 Dec 2025", title:"Draft Central Rules Published — G.S.R. 935(E)", sub:"Draft SS (Central) Rules published with 45-day window for objections and suggestions from all stakeholders.", color:"#E8A020"},
    {date:"8 May 2026",  title:"✅ Final Rules Notified — G.S.R. 344(E)",     sub:"69 Rules across 14 Chapters, 30 Forms (FORM-I to XXX). Rules effective from date of publication. Supersedes 12 earlier sets of rules.", color:"#2ECC9A"},
    {date:"22 Jun 2026", title:"⚠️ Aggregator API Data Sharing Deadline",     sub:"All aggregators must share existing gig and platform worker details via API with Central Government portal within 45 days of commencement.", color:"#2E6FED"},
    {date:"30 Jun 2026", title:"📋 Aggregator Provisional FORM-XX Due",       sub:"Every aggregator files provisional contribution return in FORM-XX. Non-filing attracts penalty action by Central Government.", color:"#1ECDE8"},
    {date:"31 Oct 2026", title:"📋 Aggregator Final FORM-XXI Due",            sub:"Final return in FORM-XXI with audited accounts. Excess refunded within 90 days with 1% monthly interest.", color:"#F07832"},
    {date:"28/29 Feb 2027", title:"📁 Annual Return FORM-XXIII Due",          sub:"Unified Annual Return (Gratuity + Maternity + IR + Safety) for 2026 filed online on MoLE portal. Covers all four Codes.", color:"#0EA5E9"}
  ]
};