// ============================================================
// INDUSTRIAL RELATIONS CODE, 2020 — COMPLETE DATA FILE
// Act No. 35 of 2020 | G.S.R. 342(E) | 8 May 2026
// In Force: 21 Nov 2025 via S.O. 5320(E)
// 104 Sections | 50 Central Rules | 16 Forms
// ============================================================

const DATA_IR = {
  meta: {
    code: "ir",
    name: "Industrial Relations Code, 2020",
    icon: "🤝",
    act: "Act No. 35 of 2020",
    sections: 104,
    rules: 50,
    forms: 16,
    enacted: "21 Nov 2025 (in force)",
    accent: "#9B72E8",
    gsr: "G.S.R. 342(E)"
  },

  stats: [
    { num: 104,   label: "Code Sections",        sub: "14 Chapters" },
    { num: 50,    label: "Central Rules",         sub: "8 May 2026" },
    { num: 16,    label: "Prescribed Forms",      sub: "FORM-I to XVI" },
    { num: 3,     label: "Schedules",             sub: "First, Second & Third" },
    { num: "20",  label: "Works Committee",       sub: "Max Members (100+ Workers)" },
    { num: "51%", label: "Negotiating Union",     sub: "Sole Union Threshold" }
  ],

  // ============================================================
  // ALL 104 SECTIONS
  // ============================================================
  sections: [
    { sec:"1",   ch:"I",    title:"Short title, extent and commencement",                provision:"Code extends to whole India. Came into force on 21st November 2025 vide S.O. 5320(E). Consolidates Trade Unions Act 1926, Industrial Employment (Standing Orders) Act 1946, Industrial Disputes Act 1947.",                                                                                                                                              app:"All Industrial Establishments" },
    { sec:"2",   ch:"I",    title:"Definitions",                                         provision:"Comprehensive definitions: appropriate Government, arbitrator, award, employer, employee, fixed-term employment, industrial dispute, industrial establishment, lay-off, lockout, retrenchment, strike, Trade Union, wages, worker etc.",                                                                                                                   app:"All" },
    { sec:"3",   ch:"II",   title:"Works Committee",                                     provision:"Industrial establishments with 100+ workers shall constitute Works Committee. Equal representation of employers and workers. Max 20 members. Functions: promote amity and good relations, comment on matters of common interest.",                                                                                                                        app:"100+ Workers" },
    { sec:"4",   ch:"II",   title:"Grievance Redressal Committee",                       provision:"Industrial establishments with 20+ workers shall constitute Grievance Redressal Committee. Max 10 members. Equal employer-worker representation. Adequate women representation. Application within 1 year of cause; decision within 30 days. Appeal to Conciliation Officer within 60 days.",                                                          app:"20+ Workers" },
    { sec:"5",   ch:"III",  title:"Registrar of Trade Unions",                           provision:"State Government may by notification appoint Registrar of Trade Unions and Additional/Joint/Deputy Registrars who shall exercise such powers as State Government may specify.",                                                                                                                                                                     app:"Trade Unions" },
    { sec:"6",   ch:"III",  title:"Criteria for registration",                           provision:"Any 7+ members may apply for Trade Union registration. Trade Union of workers registered only if at least 10% of workers or 100 workers (whichever less) engaged in establishment are members on application date.",                                                                                                                                   app:"Trade Unions" },
    { sec:"7",   ch:"III",  title:"Provisions to be contained in constitution of Trade Union", provision:"Rules must specify: name, objects, membership register, subscription, conditions of benefits, annual general body meeting, election of office-bearers every 3 years, safe custody of funds, annual audit, rules amendment, dissolution.",                                                                                                        app:"Trade Unions" },
    { sec:"8",   ch:"III",  title:"Application for registration and procedure thereof",  provision:"Application made electronically or otherwise accompanied by: declaration by affidavit, copy of rules with resolution, resolution authorising applicants, general statement of assets/liabilities if existing more than 1 year.",                                                                                                                        app:"Trade Unions" },
    { sec:"9",   ch:"III",  title:"Registration and cancellation of Trade Union",         provision:"Registrar registers by entering particulars and issues certificate. Cancellation grounds: application by union, contravention of Code, members fall below 10% or 100 workers. 60-day prior notice for cancellation.",                                                                                                                                  app:"Trade Unions" },
    { sec:"10",  ch:"III",  title:"Appeal against non-registration or cancellation",      provision:"Person aggrieved by refusal/cancellation may appeal to Tribunal within prescribed period. Tribunal after hearing may dismiss appeal or direct Registrar to register/set aside cancellation.",                                                                                                                                                          app:"Trade Unions" },
    { sec:"11",  ch:"III",  title:"Communication to Trade Union",                        provision:"All communications/notices to be sent to registered head office. Trade Union to inform Registrar if members fall below threshold; also to inform of any change in particulars, constitution or rules.",                                                                                                                                                 app:"Trade Unions" },
    { sec:"12",  ch:"III",  title:"Incorporation of a registered Trade Union",            provision:"Every registered Trade Union is a body corporate with perpetual succession and common seal; may acquire and hold property, contract, sue and be sued.",                                                                                                                                                                                              app:"Trade Unions" },
    { sec:"13",  ch:"III",  title:"Certain Acts not to apply to registered Trade Unions", provision:"Societies Registration Act 1860, Co-operative Societies Act 1912, Companies Act 2013 and corresponding State laws shall NOT apply to registered Trade Unions.",                                                                                                                                                                                      app:"Trade Unions" },
    { sec:"14",  ch:"III",  title:"Recognition of negotiating union or negotiating council", provision:"Sole negotiating union if 51%+ workers on muster roll. If no union has 51%+, negotiating council formed with unions having 20%+ workers. Verification by secret ballot. Valid 3 years (extendable to max 5 years).",                                                                                                                               app:"Industrial Establishments" },
    { sec:"15",  ch:"III",  title:"Objects of general fund, separate fund and membership fee", provision:"General funds spent only on prescribed objects. Trade Union may constitute separate fund for civic/political interests from separate contributions. No member compelled to contribute.",                                                                                                                                                            app:"Trade Unions" },
    { sec:"16",  ch:"III",  title:"Immunity from civil suit in certain cases",           provision:"No suit against registered Trade Union/office-bearer/member for acts done in contemplation/furtherance of industrial dispute on ground that it induces breach of employment contract.",                                                                                                                                                               app:"Trade Unions" },
    { sec:"17",  ch:"III",  title:"Criminal conspiracy in furtherance of Trade Union objects", provision:"No office-bearer/member liable under criminal conspiracy provision for agreement between members furthering Trade Union objects, unless agreement is to commit an offence.",                                                                                                                                                                       app:"Trade Unions" },
    { sec:"18",  ch:"III",  title:"Enforceability of agreements",                        provision:"Agreement between members of registered Trade Union not void/voidable merely because objects are in restraint of trade.",                                                                                                                                                                                                                             app:"Trade Unions" },
    { sec:"19",  ch:"III",  title:"Right to inspect books of Trade Union",               provision:"Account books and members list open to inspection by office-bearers and members at times provided in rules.",                                                                                                                                                                                                                                         app:"Trade Unions" },
    { sec:"20",  ch:"III",  title:"Rights of minor to membership of Trade Union",         provision:"Person who has attained age of 14 years and employed in non-hazardous industry may be member of registered Trade Union subject to its rules.",                                                                                                                                                                                                       app:"Trade Unions" },
    { sec:"21",  ch:"III",  title:"Disqualification of office-bearers of Trade Unions",  provision:"Disqualified if: (i) under 18; (ii) convicted for offence involving moral turpitude (5-year bar after release); (iii) Tribunal directed disqualification; (iv) Ministers or persons holding office of profit.",                                                                                                                                       app:"Trade Unions" },
    { sec:"22",  ch:"III",  title:"Adjudication of disputes of Trade Unions",             provision:"Disputes between Trade Unions, between members and union (registration/management/election), refusal of admission, federation disputes — application to Tribunal. Civil court jurisdiction barred.",                                                                                                                                                  app:"Trade Unions" },
    { sec:"23",  ch:"III",  title:"Proportion of office-bearers to be connected with industry", provision:"Unorganised sector: not less than half of total office-bearers must be actually engaged in establishment/industry. Other sectors: all except not more than 1/3 or 5 (whichever less) must be employees.",                                                                                                                                     app:"Trade Unions" },
    { sec:"24",  ch:"III",  title:"Change of name, amalgamation, notice of change",       provision:"Trade Union may change name (2/3 majority); may amalgamate as prescribed. Notice in writing signed by secretary and 7 members to be sent to Registrar.",                                                                                                                                                                                            app:"Trade Unions" },
    { sec:"25",  ch:"III",  title:"Dissolution",                                          provision:"Notice of dissolution signed by 7 members and secretary sent to Registrar within 14 days. Registrar registers if compliant. If rules silent on fund distribution, Registrar divides funds among members.",                                                                                                                                            app:"Trade Unions" },
    { sec:"26",  ch:"III",  title:"Annual returns",                                       provision:"Annual general statement forwarded to Registrar on/before prescribed date with audited particulars of receipts/expenditure/assets/liabilities for year ending 31 December. Statement of changes in office-bearers + rules copy. Alterations sent within 15 days.",                                                                                    app:"Trade Unions" },
    { sec:"27",  ch:"III",  title:"Recognition of Trade Unions at Central and State level", provision:"Central Government may recognise Trade Union/federation as Central Trade Union; State Government may recognise as State Trade Union.",                                                                                                                                                                                                              app:"Trade Unions" },
    { sec:"28",  ch:"IV",   title:"Application of Standing Orders Chapter",               provision:"Applies to every industrial establishment with 300 or more workers employed (or were employed) on any day of preceding 12 months. Does not apply to workers under Government service rules.",                                                                                                                                                          app:"300+ Workers" },
    { sec:"29",  ch:"IV",   title:"Model Standing Orders",                                provision:"Central Government makes Model Standing Orders. Until employer's Standing Orders are certified, Model Standing Orders deemed adopted.",                                                                                                                                                                                                               app:"300+ Workers" },
    { sec:"30",  ch:"IV",   title:"Preparation of draft standing orders",                 provision:"Employer to prepare draft within 6 months of Chapter applicability. Adoption of Model SO = deemed certified. Certification within 60 days of receipt.",                                                                                                                                                                                             app:"300+ Workers" },
    { sec:"31",  ch:"IV",   title:"Certifying officer and appellate authority powers",    provision:"Have civil court powers: receiving evidence, administering oath, enforcing attendance, compelling production of documents. Clerical/arithmetical errors correctable.",                                                                                                                                                                                 app:"300+ Workers" },
    { sec:"32",  ch:"IV",   title:"Appeals",                                              provision:"Employer/Trade Union/negotiating union/council may appeal certifying officer's order to Appellate Authority within 60 days of receipt.",                                                                                                                                                                                                             app:"300+ Workers" },
    { sec:"33",  ch:"IV",   title:"Date of operation of standing orders",                 provision:"Standing Orders come into operation on expiry of 30 days from authenticated copies being sent (or 7 days from appellate authority order). Text maintained in prescribed language for workers' information.",                                                                                                                                           app:"300+ Workers" },
    { sec:"34",  ch:"IV",   title:"Register of standing orders",                          provision:"Certifying officer files copy of all certified Standing Orders in register/electronic form. Furnishes copy on payment of prescribed fee.",                                                                                                                                                                                                           app:"300+ Workers" },
    { sec:"35",  ch:"IV",   title:"Duration and modification of standing orders",         provision:"Standing Orders not modifiable for 6 months from date of operation, except by agreement between employer-workers/Trade Union. Application for modification to certifying officer.",                                                                                                                                                                   app:"300+ Workers" },
    { sec:"36",  ch:"IV",   title:"Oral evidence in contradiction of standing orders not admissible", provision:"No oral evidence having effect of adding to or varying/contradicting certified Standing Orders shall be admitted in any Court.",                                                                                                                                                                                                         app:"300+ Workers" },
    { sec:"37",  ch:"IV",   title:"Interpretation of standing orders",                    provision:"Questions on application/interpretation of certified Standing Orders referred to Tribunal having territorial jurisdiction. Tribunal's decision is final and binding.",                                                                                                                                                                                 app:"300+ Workers" },
    { sec:"38",  ch:"IV",   title:"Time-limit for disciplinary proceedings and subsistence allowance", provision:"Worker suspended pending inquiry: investigation/inquiry ordinarily within 90 days. Subsistence allowance: 50% wages for first 90 days; 75% for remaining period if delay not attributable to worker.",                                                                                                                                   app:"300+ Workers" },
    { sec:"39",  ch:"IV",   title:"Power to exempt",                                      provision:"Appropriate Government may by notification exempt conditionally/unconditionally any industrial establishment or class from all or any provisions of this Chapter.",                                                                                                                                                                                   app:"300+ Workers" },
    { sec:"40",  ch:"V",    title:"Notice of change",                                     provision:"No employer to effect change in service conditions on Third Schedule matters without 21 days' notice in prescribed manner (Form-IV) to affected workers.",                                                                                                                                                                                           app:"All Establishments" },
    { sec:"41",  ch:"V",    title:"Power of appropriate Government to exempt",            provision:"Appropriate Government may by notification direct Section 40 shall not apply (or apply subject to conditions) to a class of industrial establishments or workers.",                                                                                                                                                                                  app:"All" },
    { sec:"42",  ch:"VI",   title:"Voluntary reference of disputes to arbitration",       provision:"Employer and workers may by written agreement refer existing/apprehended industrial dispute to arbitration before reference to Tribunal. Arbitration agreement in prescribed form (Form-V).",                                                                                                                                                          app:"All" },
    { sec:"43",  ch:"VII",  title:"Conciliation officers",                                provision:"Appropriate Government by notification appoints conciliation officers charged with mediating and promoting settlement of industrial disputes.",                                                                                                                                                                                                       app:"All" },
    { sec:"44",  ch:"VII",  title:"Industrial Tribunal",                                  provision:"Appropriate Government constitutes Industrial Tribunals. Two members: Judicial Member + Administrative Member. Judicial Member presides.",                                                                                                                                                                                                            app:"All" },
    { sec:"45",  ch:"VII",  title:"Finality of constitution of Tribunal",                 provision:"No notification appointing Judicial/Administrative Member can be called in question. No act/proceeding invalid by reason of vacancy or defect in constitution.",                                                                                                                                                                                     app:"All" },
    { sec:"46",  ch:"VII",  title:"National Industrial Tribunal",                         provision:"Central Government may constitute National Industrial Tribunal for disputes involving national importance or affecting establishments in more than one State.",                                                                                                                                                                                        app:"All" },
    { sec:"47",  ch:"VII",  title:"Decision of Tribunal or National Industrial Tribunal",  provision:"Decision by consensus of members. If members differ, point referred to appropriate Government which appoints Judicial Member of other Tribunal/NIT to decide.",                                                                                                                                                                                     app:"All" },
    { sec:"48",  ch:"VII",  title:"Disqualifications for members of Tribunal",             provision:"Person not appointed if not independent (connected to dispute or industry) or has attained 65 years of age.",                                                                                                                                                                                                                                       app:"All" },
    { sec:"49",  ch:"VII",  title:"Procedure and powers of arbitrator, conciliation officer, Tribunal", provision:"Civil court powers: enforcing attendance, examining on oath, compelling production of documents, issuing commissions.",                                                                                                                                                                                                                app:"All" },
    { sec:"50",  ch:"VII",  title:"Powers of Tribunal to give appropriate relief in case of discharge or dismissal", provision:"Tribunal/NIT may set aside discharge/dismissal/termination order if not justified, direct reinstatement with conditions, or award lesser punishment.",                                                                                                                                                                     app:"All" },
    { sec:"51",  ch:"VII",  title:"Transfer of pending cases",                            provision:"Pending cases before Labour Court/Tribunal under repealed Industrial Disputes Act 1947 transferred to Tribunal under this Code.",                                                                                                                                                                                                                    app:"All" },
    { sec:"53",  ch:"VII",  title:"Conciliation and adjudication of dispute",             provision:"Conciliation officer holds proceedings (not after 2 years from dispute). Investigate, induce settlement. Settlement report or failure report to Government within 45 days (or 14 days if Sec 62 notice received).",                                                                                                                                   app:"All" },
    { sec:"54",  ch:"VII",  title:"Reference to National Industrial Tribunal",            provision:"Central Government may refer industrial dispute to NIT involving national importance or affecting establishments in more than one State.",                                                                                                                                                                                                            app:"All" },
    { sec:"55",  ch:"VII",  title:"Form of award and commencement",                       provision:"Award in writing signed by Judicial/Administrative Member. Communicated to parties. Enforceable after 30 days of communication unless declaration on public grounds.",                                                                                                                                                                               app:"All" },
    { sec:"56",  ch:"VII",  title:"Payment of full wages to worker pending proceedings in Higher Courts", provision:"Where Tribunal/NIT directs reinstatement and employer challenges in HC/SC, employer pays full wages last drawn during pendency.",                                                                                                                                                                                                     app:"All" },
    { sec:"57",  ch:"VII",  title:"Persons on whom settlements and awards are binding",   provision:"Settlement outside conciliation binds parties to agreement. Conciliation settlement/arbitration award/Tribunal award binds all parties, heirs/successors/assigns of employer, all workers present or future.",                                                                                                                                         app:"All" },
    { sec:"58",  ch:"VII",  title:"Period of operation of settlements and awards",        provision:"Settlement: operative from agreed date or signing date. Award: 1 year (Government may extend up to total 3 years). Termination by 60-day notice.",                                                                                                                                                                                                   app:"All" },
    { sec:"59",  ch:"VII",  title:"Recovery of money due from employer",                  provision:"Worker may apply for recovery of money due under settlement/award/Chapters IX-X within 1 year. Government issues certificate; Collector recovers as arrear of land revenue.",                                                                                                                                                                        app:"All" },
    { sec:"60",  ch:"VII",  title:"Commencement and conclusion of proceedings",           provision:"Conciliation: commences on date of first meeting after notice/reference. Arbitrator/Tribunal: commences on filing/reference date.",                                                                                                                                                                                                                 app:"All" },
    { sec:"61",  ch:"VII",  title:"Certain matters to be kept confidential",              provision:"Information about Trade Union/individual business not otherwise available shall not be included in report/award if written request for confidentiality made.",                                                                                                                                                                                        app:"All" },
    { sec:"62",  ch:"VIII", title:"Prohibition of strikes and lock-outs",                provision:"No strike without: 60-day notice; or within 14 days of giving notice; or before specified date; during conciliation proceedings or 7 days after; during Tribunal/NIT proceedings or 60 days after.",                                                                                                                                                   app:"All Industrial Establishments" },
    { sec:"63",  ch:"VIII", title:"Illegal strikes and lock-outs",                        provision:"Strike/lockout illegal if: commenced/declared in contravention of Section 62; continued in contravention of order under Sec 42(7).",                                                                                                                                                                                                                app:"All" },
    { sec:"64",  ch:"VIII", title:"Prohibition of financial aid to illegal strikes or lock-outs", provision:"No person to knowingly spend or apply any money in direct furtherance or support of any illegal strike or lockout.",                                                                                                                                                                                                                         app:"All" },
    { sec:"65",  ch:"IX",   title:"Application of sections 67 to 69",                    provision:"Sections 67-69 do NOT apply to: (a) industrial establishments under Chapter X; (b) establishments with less than 50 workers on average preceding month; (c) seasonal/intermittent establishments.",                                                                                                                                                   app:"50+ Workers" },
    { sec:"66",  ch:"IX",   title:"Definition of continuous service",                     provision:"Continuous service = uninterrupted service including sickness/authorised leave/accident/legal strike/lockout. Deemed continuous: 1 year if worked 190 days (mines) or 240 days (others) in 12 months.",                                                                                                                                               app:"All" },
    { sec:"67",  ch:"IX",   title:"Rights of workers laid-off for compensation",          provision:"Laid-off worker (other than badli/casual) with 1+ year continuous service: 50% of basic wages + DA for laid-off days (except weekly holidays).",                                                                                                                                                                                                    app:"Lay-off" },
    { sec:"68",  ch:"IX",   title:"Duty to maintain muster rolls during lay-off",        provision:"Even during lay-off, employer must maintain muster roll and provide for entries by workers presenting themselves at establishment at appointed time during normal working hours.",                                                                                                                                                                      app:"Lay-off" },
    { sec:"69",  ch:"IX",   title:"Workers not entitled for compensation in certain cases", provision:"No lay-off compensation if worker: (i) refuses alternative employment in same/nearby establishment (within 8 km); (ii) does not present himself once a day; (iii) lay-off due to strike/slowdown.",                                                                                                                                                 app:"Lay-off" },
    { sec:"70",  ch:"IX",   title:"Conditions precedent to retrenchment of workers",      provision:"Worker with 1+ year continuous service retrenched only if: (a) 1 month notice in writing with reasons, or wages in lieu; (b) compensation = 15 days' average pay × completed years (above 6 months).",                                                                                                                                              app:"Retrenchment" },
    { sec:"71",  ch:"IX",   title:"Procedure for retrenchment",                          provision:"Citizen worker of particular category: employer shall ordinarily retrench last employed worker (last-come-first-go), unless reasons recorded for deviation.",                                                                                                                                                                                         app:"Retrenchment" },
    { sec:"72",  ch:"IX",   title:"Re-employment of retrenched worker",                   provision:"If employer proposes to take any person into employment within 1 year of retrenchment, prescribed opportunity to be given to retrenched workers (citizens of India).",                                                                                                                                                                                app:"Retrenchment" },
    { sec:"73",  ch:"IX",   title:"Compensation on transfer of establishment",            provision:"On transfer of ownership/management, worker with 1+ year continuous service entitled to notice and compensation as if retrenched (Sec 70).",                                                                                                                                                                                                        app:"Transfer" },
    { sec:"74",  ch:"IX",   title:"60 days notice of intention to close down",           provision:"Employer intending closure: 60-day notice in prescribed manner to appropriate Government stating reasons. Exceptions: <50 workers in preceding 12 months; construction undertakings.",                                                                                                                                                                 app:"Closure" },
    { sec:"75",  ch:"IX",   title:"Compensation to workers in case of closing down",      provision:"Closure: every worker with 1+ year continuous service entitled to notice and compensation as if retrenched (Sec 70). Closure due to unavoidable circumstances: max 3 months' average pay.",                                                                                                                                                          app:"Closure" },
    { sec:"76",  ch:"IX",   title:"Effect of laws inconsistent with this Chapter",        provision:"Chapter IX overrides other laws/standing orders/awards/contracts. Worker entitled to more favourable benefits under other instruments continues to receive those.",                                                                                                                                                                                   app:"All" },
    { sec:"77",  ch:"X",    title:"Application of Chapter X",                             provision:"Applies to industrial establishments (not seasonal/intermittent) with 300+ workers employed on average per working day in preceding 12 months.",                                                                                                                                                                                                     app:"300+ Workers" },
    { sec:"78",  ch:"X",    title:"Prohibition of lay-off (300+ workers)",                provision:"No lay-off (other than badli/casual) without PRIOR PERMISSION of appropriate Government. Exception: shortage of power, natural calamity, mine fire/flood/gas/explosion (apply within 30 days). 60-day Government decision (deemed granted otherwise).",                                                                                              app:"300+ Workers" },
    { sec:"79",  ch:"X",    title:"Retrenchment of workers (300+ workers)",               provision:"Worker with 1+ year continuous service: 3 months' notice in writing OR wages in lieu + PRIOR PERMISSION for retrenchment. 60-day Government decision. Compensation: 15 days' average pay × completed years.",                                                                                                                                       app:"300+ Workers" },
    { sec:"80",  ch:"X",    title:"Closure procedure (300+ workers)",                     provision:"PRIOR PERMISSION application 90 days before intended closure date with reasons. Copy to workers' representatives. 60-day Government decision (deemed granted otherwise).",                                                                                                                                                                           app:"300+ Workers" },
    { sec:"81",  ch:"X",    title:"Duty to maintain muster rolls during lay-off (Chapter X)", provision:"Even during lay-off, employer must maintain muster roll and provide for worker entries at appointed time during normal working hours.",                                                                                                                                                                                                           app:"300+ Workers" },
    { sec:"82",  ch:"X",    title:"Certain provisions of Chapter IX to apply to Chapter X", provision:"Provisions of Sections 66, 71, 72, 73, and 76 of Chapter IX also apply to establishments under Chapter X.",                                                                                                                                                                                                                                      app:"300+ Workers" },
    { sec:"83",  ch:"XI",   title:"Worker re-skilling fund",                              provision:"Appropriate Government to set up Worker Re-skilling Fund. Employer contributes 15 days' wages last drawn for every retrenched worker. Credited to retrenched worker's account within 45 days.",                                                                                                                                                       app:"All Employers" },
    { sec:"84",  ch:"XII",  title:"Prohibition of unfair labour practice",                provision:"No employer, worker, or Trade Union (whether registered or not) shall commit any unfair labour practice specified in the Second Schedule.",                                                                                                                                                                                                          app:"All" },
    { sec:"85",  ch:"XIII", title:"Power of officers to impose penalty",                  provision:"Appropriate Government may appoint officer to hold inquiry and impose penalty. Failure to pay penalty within 90 days: fine ₹50,000–₹2 lakh.",                                                                                                                                                                                                       app:"All" },
    { sec:"86",  ch:"XIII", title:"Penalties",                                            provision:"Sec 78/79/80 contravention: ₹1L–₹10L fine; repeat ₹5L–₹20L + imprisonment 6 months. Sec 67/70/73/75: ₹50K–₹2L fine. Unfair labour practice: ₹10K–₹2L. Trade Union default: ₹1K–₹10K.",                                                                                                                                                           app:"All" },
    { sec:"87",  ch:"XIII", title:"Cognizance of offences",                               provision:"No court takes cognizance except on complaint made by or under authority of appropriate Government. No court inferior to Metropolitan Magistrate/Judicial Magistrate First Class tries offences.",                                                                                                                                                     app:"All" },
    { sec:"88",  ch:"XIII", title:"Offences by companies",                                provision:"If offence committed by company, every person in-charge and responsible for conduct of business at the time, as well as the company, deemed guilty.",                                                                                                                                                                                               app:"All" },
    { sec:"89",  ch:"XIII", title:"Composition of offences",                              provision:"Offences not punishable with imprisonment only may be compounded for 50% of max fine (fine-only offences) or 75% (imprisonment up to 1 year). Amount credited to Social Security Fund.",                                                                                                                                                             app:"All" },
    { sec:"90",  ch:"XIV",  title:"Conditions of service to remain unchanged during pendency of proceedings", provision:"During pendency of industrial dispute, employer cannot alter service conditions to worker's prejudice or discharge/punish for connected misconduct without authority's permission.",                                                                                                                                               app:"All" },
    { sec:"91",  ch:"XIV",  title:"Special provision for adjudication of changed conditions", provision:"Where employer contravenes Sec 90 during pendency, aggrieved employee may file complaint in Form-XVI.",                                                                                                                                                                                                                                          app:"All" },
    { sec:"92",  ch:"XIV",  title:"Power to transfer certain proceedings",                provision:"Appropriate Government may transfer pending proceedings from one Tribunal to another.",                                                                                                                                                                                                                                                              app:"All" },
    { sec:"93",  ch:"XIV",  title:"Protection of persons",                                provision:"No person refusing to take part in illegal strike/lockout liable to expulsion from Trade Union/society, fine, penalty, deprivation of right.",                                                                                                                                                                                                      app:"All" },
    { sec:"94",  ch:"XIV",  title:"Representation of parties",                            provision:"Worker may be represented by Trade Union office-bearer (if member), federation office-bearer, or co-worker authorised in Form-VI. No legal practitioner in conciliation.",                                                                                                                                                                           app:"All" },
    { sec:"95",  ch:"XIV",  title:"Removal of doubts in interpretation of award",         provision:"If appropriate Government opines difficulty/doubt arises in interpretation of award/settlement, may refer to Tribunal/NIT.",                                                                                                                                                                                                                         app:"All" },
    { sec:"96",  ch:"XIV",  title:"Power to exempt",                                      provision:"Appropriate Government may exempt (conditionally/unconditionally) establishment from any provision where adequate provisions exist.",                                                                                                                                                                                                                 app:"All" },
    { sec:"97",  ch:"XIV",  title:"Jurisdiction of civil courts barred",                  provision:"No civil court has jurisdiction in respect of any matter to which any provision of this Code applies.",                                                                                                                                                                                                                                             app:"All" },
    { sec:"98",  ch:"XIV",  title:"Protection of action taken in good faith",              provision:"No suit, prosecution or other legal proceeding lies against any person for anything done in good faith in pursuance of this Code or rules made thereunder.",                                                                                                                                                                                         app:"All" },
    { sec:"99",  ch:"XIV",  title:"Power of appropriate Government to make rules",        provision:"Appropriate Government may, subject to previous publication, make rules for giving effect to Code. Rules laid before Parliament/State Legislature.",                                                                                                                                                                                                 app:"All" },
    { sec:"100", ch:"XIV",  title:"Delegation of powers",                                 provision:"Appropriate Government may by notification direct that any power exercisable by it be exercisable also by subordinate officer/authority.",                                                                                                                                                                                                          app:"All" },
    { sec:"101", ch:"XIV",  title:"Power to amend Schedules",                             provision:"Central Government may by notification add to/alter/amend First, Second, and Third Schedules. Notifications laid before Parliament for 30 days.",                                                                                                                                                                                                   app:"All" },
    { sec:"102", ch:"XIV",  title:"Amendment of Act 7 of 2017",                          provision:"Finance Act 2017, Eighth Schedule, Serial No. 1: substitutes 'Industrial Tribunal constituted by the Central Government under Section 44(1) of the Industrial Relations Code, 2020'.",                                                                                                                                                               app:"All" },
    { sec:"103", ch:"XIV",  title:"Power to remove difficulties",                         provision:"Central Government may by order published in Official Gazette make provisions to remove implementation difficulties within 3 years of Code commencement.",                                                                                                                                                                                           app:"All" },
    { sec:"104", ch:"XIV",  title:"Repeal and savings",                                   provision:"Repeals 3 earlier labour laws: (a) Trade Unions Act 1926; (b) Industrial Employment (Standing Orders) Act 1946; (c) Industrial Disputes Act 1947. Actions taken under repealed Acts deemed taken under this Code.",                                                                                                                                   app:"All" }
  ],

  // ============================================================
  // ALL 50 CENTRAL RULES — G.S.R. 342(E), 8 May 2026
  // ============================================================
  rules: [
    { r:"1",  ch:"I",    t:"Short title and commencement — Industrial Relations (Central) Rules, 2026 effective from publication",                                               c:"Preliminary",      thresh:"All",                     codeRef:"Sec 1" },
    { r:"2",  ch:"I",    t:"Definitions — Code, electronically, Form, section and other key terms",                                                                              c:"Preliminary",      thresh:"All",                     codeRef:"Sec 2" },
    { r:"3",  ch:"I",    t:"References of certain authorities — Administrator for UTs without legislature; Officer-in-charge for railways/government undertakings",              c:"Preliminary",      thresh:"All",                     codeRef:"Sec 2" },
    { r:"4",  ch:"I",    t:"Memorandum of settlement — FORM-I; signed by employer and workers; copy to conciliation officer/Deputy CLC(C)",                                      c:"Conciliation",     thresh:"All",                     codeRef:"Sec 2, Sec 53" },
    { r:"5",  ch:"II",   t:"Works Committee — max 20 members; equal reps; women proportional; term 3 years; meetings at least every 3 months",                                  c:"Works Committee",  thresh:"100+ Workers",            codeRef:"Sec 3" },
    { r:"6",  ch:"II",   t:"Grievance Redressal Committee — max 10 members; equal representation; women representation; term 3 years",                                          c:"Grievance",        thresh:"20+ Workers",             codeRef:"Sec 4" },
    { r:"7",  ch:"II",   t:"Grievance Application — name, designation, code, department, service length, grievance details, relief sought; within 1 year of cause",             c:"Grievance",        thresh:"20+ Workers",             codeRef:"Sec 4" },
    { r:"8",  ch:"II",   t:"Application to conciliation officer — within 60 days of GRC decision or expiry of 30 days; online MoLE portal through Trade Union",                 c:"Conciliation",     thresh:"All",                     codeRef:"Sec 4" },
    { r:"9",  ch:"III",  t:"Recognition of negotiating union/council — sole union 51%+; verification by secret ballot; valid 3-5 years",                                        c:"Trade Union",      thresh:"All",                     codeRef:"Sec 14" },
    { r:"10", ch:"IV",   t:"Model Standing Orders — adoption and intimation to Certifying Officer electronically/by speed post; deemed certified in 30 days",                   c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 29, Sec 30" },
    { r:"11", ch:"IV",   t:"Choosing representatives of workers where there is no Trade Union — Certifying Officer calls meeting; 15 days for comments",                        c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 30" },
    { r:"12", ch:"IV",   t:"Authentication of certified standing order — sent electronically + hard copy by speed post within 7 days",                                          c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 30" },
    { r:"13", ch:"IV",   t:"Statement to accompany draft standing orders — name, address, email, employee details, Trade Union particulars; tabular for modifications",          c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 30" },
    { r:"14", ch:"IV",   t:"Conditions for joint draft standing orders — group of employers may submit joint draft to Additional CLC(C)",                                        c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 30" },
    { r:"15", ch:"IV",   t:"Disposal of appeal — within 60 days; appeal in tabular form with reasons; appellate authority decision",                                            c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 32" },
    { r:"16", ch:"IV",   t:"Serving of order and text of standing orders — within 3 days; Hindi/English/local language; entrance + portal display",                             c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 33" },
    { r:"17", ch:"IV",   t:"Register of standing orders — FORM-III; Certifying Officer maintains electronically; unique number; certification date; copy at ₹2/page",          c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 34" },
    { r:"18", ch:"IV",   t:"Application for modification of standing orders — electronic/speed post; tabular statement of proposed modifications",                              c:"Standing Orders",  thresh:"300+ Workers",            codeRef:"Sec 35" },
    { r:"19", ch:"V",    t:"Notice for change — FORM-IV; 21 days notice for Third Schedule matters; portal display; copy to Trade Union",                                       c:"Notice of Change", thresh:"All",                     codeRef:"Sec 40" },
    { r:"20", ch:"VI",   t:"Form of arbitration agreement — FORM-V; signed by employer and workers; arbitrator written/electronic consent; 60-day default period",              c:"Arbitration",      thresh:"All",                     codeRef:"Sec 42" },
    { r:"21", ch:"VI",   t:"Issuing of notification — Central Government publishes arbitration notification in Official Gazette and MoLE website",                              c:"Arbitration",      thresh:"All",                     codeRef:"Sec 42" },
    { r:"22", ch:"VI",   t:"Choosing representatives of workers where no Trade Union — majority resolution in FORM-VI",                                                         c:"Arbitration",      thresh:"All",                     codeRef:"Sec 42" },
    { r:"23", ch:"VII",  t:"Conciliation proceedings — designated portal entry; settlement report on portal within 7 days; failure report within 45 days; affidavit evidence", c:"Conciliation",     thresh:"All",                     codeRef:"Sec 43, Sec 53" },
    { r:"24", ch:"VII",  t:"Application for recovery of dues — FORM-VII (worker); FORM-VIII (authorized/assignee/heir); FORM-IX (Tribunal); FORM-X (heir for Tribunal)",       c:"Recovery",         thresh:"All",                     codeRef:"Sec 59" },
    { r:"25", ch:"VIII", t:"Notice of strike — FORM-XI; 60-day notice; Trade Union Secretary or 5 elected representatives; copies to Conciliation Officer/CLC(C)/MoLE",        c:"Strikes",          thresh:"All",                     codeRef:"Sec 62" },
    { r:"26", ch:"VIII", t:"Notice of lock-out — FORM-XII; 60-day notice to Trade Union Secretary; speed post/electronic; conspicuous display",                                 c:"Strikes",          thresh:"All",                     codeRef:"Sec 62" },
    { r:"27", ch:"IX",   t:"Service of notice before retrenchment — FORM-XIII; 30-day notice to Central Government + Deputy CLC(C) via email/speed post",                      c:"Lay-off/Closure",  thresh:"All",                     codeRef:"Sec 70" },
    { r:"28", ch:"IX",   t:"Re-employment to retrenched workers — seniority list 7 days before; preference for citizens in vacancies; 15-day vacancy notice",                  c:"Lay-off/Closure",  thresh:"All",                     codeRef:"Sec 72" },
    { r:"29", ch:"IX",   t:"Service of notice for intended closure — FORM-XIII; 60 days notice; copy to Trade Unions/workers representatives",                                  c:"Lay-off/Closure",  thresh:"All",                     codeRef:"Sec 74" },
    { r:"30", ch:"X",    t:"Application for intended lay-off — FORM-XIV to Central Government 15 days before; workers served simultaneously; conspicuous display",              c:"Lay-off/Closure",  thresh:"300+ Workers",            codeRef:"Sec 78" },
    { r:"31", ch:"X",    t:"Application to continue lay-off in mines — fire/flood/gas/explosion; FORM-XIV within 30 days specifying days, workers, reasons",                   c:"Lay-off/Closure",  thresh:"Mines",                   codeRef:"Sec 78" },
    { r:"32", ch:"X",    t:"Review of lay-off order — Government may review suo-motu or on application within 30 days; disposal within 2 months",                              c:"Lay-off/Closure",  thresh:"300+ Workers",            codeRef:"Sec 78" },
    { r:"33", ch:"X",    t:"Application for intended retrenchment — FORM-XIV electronically; copy to workers; conspicuous display 60 days before",                              c:"Lay-off/Closure",  thresh:"300+ Workers",            codeRef:"Sec 79" },
    { r:"34", ch:"X",    t:"Review of retrenchment order — application within 30 days; disposal within 2 months with hearing; suo-motu review within 1 month",                 c:"Lay-off/Closure",  thresh:"300+ Workers",            codeRef:"Sec 79" },
    { r:"35", ch:"X",    t:"Application for intended closure — FORM-XIV; 90 days before; copy to representatives electronically/in-person/speed post",                         c:"Lay-off/Closure",  thresh:"300+ Workers",            codeRef:"Sec 80" },
    { r:"36", ch:"X",    t:"Review of closure order — application within 30 days; disposal within 2 months; hearing opportunity",                                               c:"Lay-off/Closure",  thresh:"300+ Workers",            codeRef:"Sec 80" },
    { r:"37", ch:"XI",   t:"Worker re-skilling fund — 15 days last wages electronically within 10 days of retrenchment to CLC(C) account; disbursed to worker within 45 days", c:"Lay-off/Closure",  thresh:"All Employers",           codeRef:"Sec 83" },
    { r:"38", ch:"XII",  t:"Composition of offence — FORM-XV (3 parts); 15-day window to deposit; certificate issued; credited to Social Security Fund",                       c:"Compounding",      thresh:"All",                     codeRef:"Sec 89" },
    { r:"39", ch:"XIII", t:"Protected workers — Trade Union informs employer by 30 April yearly; 1% of workers (min 5, max 100); recognition valid 12 months",                  c:"Trade Union",      thresh:"All",                     codeRef:"Sec 90" },
    { r:"40", ch:"XIII", t:"Complaint by aggrieved employee — FORM-XVI electronically or speed post; copies for each opposite party; verification by complainant",               c:"Grievance",        thresh:"All",                     codeRef:"Sec 91" },
    { r:"41", ch:"XIII", t:"Authorisation of worker for representing in proceeding — FORM-VI; non-union worker may authorize any Trade Union officer or co-worker",              c:"Misc",             thresh:"All",                     codeRef:"Sec 94" },
    { r:"42", ch:"XIII", t:"Authorisation of employer for representing in proceeding — FORM-VI; non-association employer may authorize any association officer",                 c:"Misc",             thresh:"All",                     codeRef:"Sec 94" },
    { r:"43", ch:"XIII", t:"Parties bound by acts of representative — party appearing through representative bound by acts",                                                     c:"Misc",             thresh:"All",                     codeRef:"Sec 94" },
    { r:"44", ch:"XIII", t:"Enquiry — Under Secretary level officer; video conferencing permitted; max 3 adjournments; Civil Procedure Code applies",                           c:"Misc",             thresh:"All",                     codeRef:"Sec 85" },
    { r:"45", ch:"XIII", t:"Expenses of witness — same as Civil Court rates of the State where enquiry/adjudication/arbitration conducted",                                     c:"Misc",             thresh:"All",                     codeRef:"Sec 49, Sec 85" },
    { r:"46", ch:"XIII", t:"Publication for communication — email/website/portal specified in letterheads of all authorities, tribunals, employers, Trade Unions",               c:"Misc",             thresh:"All",                     codeRef:"Sec 99" },
    { r:"47", ch:"XIII", t:"Maintenance of records and registers — electronic maintenance; produced on demand to authority",                                                     c:"Misc",             thresh:"All",                     codeRef:"Sec 99" },
    { r:"48", ch:"XIII", t:"Appointment of Commissioner — industry-experienced person, retired civil court judge, stipendiary magistrate, or Tribunal Registrar",               c:"Misc",             thresh:"All",                     codeRef:"Sec 59" },
    { r:"49", ch:"XIII", t:"Fee for Commissioner — estimated by Tribunal after consultation; deposited by parties; instalments; variation possible",                             c:"Misc",             thresh:"All",                     codeRef:"Sec 59" },
    { r:"50", ch:"XIII", t:"Time for submission of Commissioner report — appointment order indicates date; extension on Commissioner application before expiry",                 c:"Misc",             thresh:"All",                     codeRef:"Sec 59" }
  ],

  // ============================================================
  // ALL 16 PRESCRIBED FORMS
  // ============================================================
  forms: [
    {
      n:"I",   ruleRef:"Rule 4",          cat:"Settlement",    codeRef:"Sec 2(zi), Sec 53",  cc:"#2E6FED", bg:"rgba(46,111,237,0.12)",
      title:"Memorandum of Settlement",
      desc:"Settlement record during conciliation or between employer and worker(s) directly. Names of parties, recital of case, terms of settlement, signatures of parties, witnesses, and conciliation officer signature. Outside conciliation: copy marked to DCLC(C).",
      who:"Employer + Workers/Trade Union", deadline:"On settlement of dispute",   filedBy:"Parties → Conciliation Officer/DCLC(C)",
      driveLink:"https://drive.google.com/file/d/18qdFWtnztGDC4FP9pc22jwY248ouU_B8/view"
    },
    {
      n:"II",  ruleRef:"Rule 9 / Rule 23", cat:"Tribunal",     codeRef:"Sec 22, Sec 53",     cc:"#9B72E8", bg:"rgba(155,114,232,0.12)",
      title:"Application to Industrial Tribunal",
      desc:"Filed by workers/Trade Union/parties after conciliation failure. Contains applicant and opposite party details, brief facts of dispute, specific issues, and prayer for adjudication.",
      who:"Workers/Trade Union/Party in dispute", deadline:"Within 90 days of conciliation report", filedBy:"Aggrieved Party → Industrial Tribunal",
      driveLink:"https://drive.google.com/file/d/1OgLMMwl0WrSE7pcyV2x9r-mG6oMewmQa/view"
    },
    {
      n:"III", ruleRef:"Rule 17",          cat:"Standing Orders", codeRef:"Sec 34",           cc:"#E8A020", bg:"rgba(232,160,32,0.12)",
      title:"Register of Certified Standing Orders",
      desc:"Electronic register maintained by Certifying Officer. Contains unique number, establishment name, nature, areas of operation, certification date, appeal details, amendments. Copy at ₹2/page.",
      who:"Certifying Officer", deadline:"Maintained continuously",               filedBy:"Certifying Officer",
      driveLink:"https://drive.google.com/file/d/1m1rXvYBdafzDGpXA8CBf62-Kntbx1gGd/view"
    },
    {
      n:"IV",  ruleRef:"Rule 19",          cat:"Notice",        codeRef:"Sec 40",             cc:"#F07832", bg:"rgba(240,120,50,0.12)",
      title:"Notice of Change of Service Conditions",
      desc:"21 days advance notice for change in Third Schedule matters (wages, hours, leave, etc.). Displayed conspicuously on notice board and electronic board. Uploaded to portal.",
      who:"Employer → Workers/Trade Union", deadline:"21 days before intended change", filedBy:"Employer",
      driveLink:"https://drive.google.com/file/d/1AT7BNBrZ8g_klVuAtbEddSW1_KWBRtSN/view"
    },
    {
      n:"V",   ruleRef:"Rule 20",          cat:"Arbitration",   codeRef:"Sec 42",             cc:"#1ECDE8", bg:"rgba(30,205,232,0.10)",
      title:"Agreement for Voluntary Arbitration",
      desc:"Tripartite arbitration agreement between employer and workers for voluntary reference of industrial dispute. Identifies specific matters in dispute, parties, workers affected, total workers in undertaking. Default period: 60 days.",
      who:"Employer + Workers/Trade Union", deadline:"Before referring to Tribunal",  filedBy:"Parties → Conciliation Officer/MoLE Secretary",
      driveLink:"https://drive.google.com/file/d/1UlsDpzMVsF3PWm9D1Dls06uVslD3nN_b/view"
    },
    {
      n:"VI",  ruleRef:"Rules 22, 41 and 42", cat:"Arbitration", codeRef:"Sec 42, Sec 94",   cc:"#1ECDE8", bg:"rgba(30,205,232,0.10)",
      title:"Authorisation for Representation in Proceedings",
      desc:"Authorization given by worker(s) or employer(s) to be represented in proceedings. Used when worker is not a Trade Union member (authorise Union officer or co-worker) or employer not in association.",
      who:"Worker/Employer → Representative", deadline:"Before proceedings commence",  filedBy:"Aggrieved Party",
      driveLink:"https://drive.google.com/file/d/1Y5nnmnxj4B41RPMPba46rS_4zKcxscyp/view"
    },
    {
      n:"VII", ruleRef:"Rule 24",          cat:"Recovery",      codeRef:"Sec 59",             cc:"#F87171", bg:"rgba(248,113,113,0.10)",
      title:"Application for Recovery of Money Due (by Worker/Group)",
      desc:"Application by worker or group for recovery of money due from employer under settlement, award, or Chapter IX/X. Requires demand notice served on employer 15 days prior to filing.",
      who:"Worker/Group of Workers", deadline:"After 15 days of demand notice non-payment", filedBy:"Worker → MoLE Secretary + Deputy CLC(C)",
      driveLink:"https://drive.google.com/file/d/1IB8-m3BfnggXVo5qUvsf8hvWR5XVmUYg/view"
    },
    {
      n:"VIII", ruleRef:"Rule 24",         cat:"Recovery",      codeRef:"Sec 59",             cc:"#F87171", bg:"rgba(248,113,113,0.10)",
      title:"Application for Recovery (by Authorized Person/Assignee/Heir)",
      desc:"Application by authorized person or assignee/heir of deceased worker for recovery of money due. Identical to Form-VII but additionally states authorization or heir status.",
      who:"Authorized Person/Assignee/Heir", deadline:"After 15 days of demand notice non-payment", filedBy:"Authorized Person → MoLE + Deputy CLC(C)",
      driveLink:"https://drive.google.com/file/d/1amX_y_fxSOMX3doSLwADul13RI1HeXrq/view"
    },
    {
      n:"IX",  ruleRef:"Rule 24",          cat:"Recovery",      codeRef:"Sec 59",             cc:"#F87171", bg:"rgba(248,113,113,0.10)",
      title:"Application to Tribunal for Computation of Money Value of Benefit",
      desc:"Application by worker to Industrial Tribunal for determining money value of non-monetary benefit due from employer. Tribunal to decide within 3 months.",
      who:"Worker/Group of Workers", deadline:"When non-monetary benefit needs valuation", filedBy:"Worker → Industrial Tribunal",
      driveLink:"https://drive.google.com/file/d/1AuhrYz3i0IAOQemumnmoNgiXFSMyj4Ew/view"
    },
    {
      n:"X",   ruleRef:"Rule 24",          cat:"Recovery",      codeRef:"Sec 59",             cc:"#F87171", bg:"rgba(248,113,113,0.10)",
      title:"Application to Tribunal by Assignee/Heir of Deceased Worker",
      desc:"Application by assignee or heir of deceased worker to Tribunal for determining money value of benefit due. Establishes applicant's status as legal assignee/heir.",
      who:"Assignee/Heir of Deceased Worker", deadline:"After worker's death",            filedBy:"Assignee/Heir → Industrial Tribunal",
      driveLink:"https://drive.google.com/file/d/1gLCAnTqZTFvJ0QJvL9Cw9_Mvt3L3y4pF/view"
    },
    {
      n:"XI",  ruleRef:"Rule 25",          cat:"Strike/Lockout", codeRef:"Sec 62",            cc:"#E858A8", bg:"rgba(232,88,168,0.12)",
      title:"Notice of Strike (by Trade Union/5 Representatives)",
      desc:"Statutory 60-day strike notice. Registered Trade Union (signed by Secretary) or 5 elected representatives. Copies to Conciliation Officer, CLC(C), Secretary MoLE. No strike during conciliation/Tribunal proceedings.",
      who:"Trade Union/Workers' Representatives", deadline:"Minimum 60 days before strike", filedBy:"Trade Union → Employer + Authorities",
      driveLink:"https://drive.google.com/file/d/1aoJZzLBRjpqy2le26t0zJA9DEd3yM1vY/view"
    },
    {
      n:"XII", ruleRef:"Rule 26",          cat:"Strike/Lockout", codeRef:"Sec 62",            cc:"#E858A8", bg:"rgba(232,88,168,0.12)",
      title:"Notice of Lock-out (by Employer)",
      desc:"Statutory 60-day lock-out notice to Secretary of every registered Trade Union by speed post/electronically. Must be displayed conspicuously at main entrance. Copies to Conciliation Officer, CLC(C), Secretary MoLE.",
      who:"Employer → Trade Union(s)", deadline:"Minimum 60 days before lockout",        filedBy:"Employer",
      driveLink:"https://drive.google.com/file/d/1nRaYHTEDTfCAbDUqmQKlD7YFG2cSbH3n/view"
    },
    {
      n:"XIII", ruleRef:"Rules 27 and 29", cat:"Retrenchment",  codeRef:"Sec 70, Sec 74",    cc:"#F07070", bg:"rgba(240,112,112,0.12)",
      title:"Notice of Retrenchment/Closure to Central Government (Chapter IX)",
      desc:"Statutory notice for: (a) Retrenchment (30 days notice) or (b) Closure (60 days notice). Submitted online to Secretary MoLE with copy to Deputy CLC(C). Includes compliance declarations and insolvency status.",
      who:"Employer → Central Government", deadline:"Retrenchment: 30 days · Closure: 60 days", filedBy:"Employer → MoLE Secretary + Deputy CLC(C)",
      driveLink:"https://drive.google.com/file/d/1F_zlN4jueLpwX2-wLm__5Yd5ApqBvxPL/view"
    },
    {
      n:"XIV", ruleRef:"Rules 30, 33 and 35", cat:"Retrenchment", codeRef:"Sec 78, Sec 79, Sec 80", cc:"#F07070", bg:"rgba(240,112,112,0.12)",
      title:"Application for Lay-off/Retrenchment/Closure Permission (Chapter X)",
      desc:"Application for prior permission for establishments with 300+ workers. Lay-off: 15 days before. Retrenchment: 60 days before. Closure: 90 days before. Comprehensive Annexure-I (establishment details) and Annexure-II (affected workers with UAN, wages, service date).",
      who:"Employer (300+ workers) → Central Government", deadline:"Lay-off: 15d · Retrench: 60d · Closure: 90d", filedBy:"Employer → MoLE Secretary",
      driveLink:"https://drive.google.com/file/d/152Efs_VwYwIVeNMBpEbQ2rsOPXiIsyUx/view"
    },
    {
      n:"XV",  ruleRef:"Rule 38",          cat:"Compounding",   codeRef:"Sec 89",             cc:"#9B72E8", bg:"rgba(155,114,232,0.10)",
      title:"Compounding Notice (Parts I, II, III)",
      desc:"PART-I: Notice by Compounding Officer. PART-II: 15-day window to deposit amount. PART-III: Application by accused with proof of deposit. Amount credited to Social Security Fund. Stops prosecution.",
      who:"Compounding Officer → Accused", deadline:"15 days for accused to deposit",     filedBy:"Compounding Officer (Notice); Accused (Application)",
      driveLink:"https://drive.google.com/file/d/1zR-U2WF5TCb3SSCBm4nbYZyFQcs6hPxk/view"
    },
    {
      n:"XVI", ruleRef:"Rule 40",          cat:"Complaint",     codeRef:"Sec 91",             cc:"#60A5FA", bg:"rgba(96,165,250,0.10)",
      title:"Complaint by Aggrieved Employee (under Sec 91)",
      desc:"Complaint against employer for contravention of Section 90 during pendency of dispute. Filed before Conciliation Officer/Arbitrator/Tribunal/National Industrial Tribunal. Electronic or speed post. Multiple copies for each opposite party.",
      who:"Aggrieved Employee", deadline:"Within 1 year of cause of action",              filedBy:"Aggrieved Employee → Authority",
      driveLink:"https://drive.google.com/file/d/1YBnBmW-RTJayA7EKtdJERIDRLgJs6-N-/view"
    }
  ],

  // ============================================================
  // EMPLOYER COMPLIANCE SECTIONS
  // ============================================================
  employerSections: [
    {
      icon: "🤝",
      title: "A. Bi-Partite Forums (Chapter II)",
      color: "rgba(155,114,232,0.12)",
      items: [
        { rule:"Rule 5",  title:"Works Committee — Max 20 Members",               cls:"wc",   codeRef:"Sec 3",  desc:"100+ workers MUST constitute Works Committee. Max 20 members. Equal employer-worker representation. Women proportional. Term: 3 years. Meets at least ONCE EVERY 3 MONTHS.",                                          thresh:"100+ Workers",         forms:[] },
        { rule:"Rule 6",  title:"Grievance Redressal Committee",                  cls:"gr",   codeRef:"Sec 4",  desc:"20+ workers MUST constitute GRC. Max 10 members. Equal representation. Adequate women representation. Term: 3 years. Resolution within 30 days. Appeal to Conciliation Officer within 60 days.",                   thresh:"20+ Workers",          forms:[] },
        { rule:"Rule 9",  title:"Trade Union Recognition — 51% Threshold",        cls:"tu",   codeRef:"Sec 14", desc:"SOLE NEGOTIATING UNION: 51%+ membership. NEGOTIATING COUNCIL: unions with 20%+ (minimum). Verification by secret ballot by Central Government-appointed verification officer. Term: 3-5 years.",                  thresh:"All Industrial Establishments", forms:[] }
      ]
    },
    {
      icon: "📜",
      title: "B. Standing Orders (Chapter IV)",
      color: "rgba(232,160,32,0.12)",
      items: [
        { rule:"Rules 10–14", title:"Standing Orders — 300+ Workers",             cls:"so",   codeRef:"Sec 28–30", desc:"300+ workers: Adopt Model SO or submit draft within 6 months. Model SO: intimate Certifying Officer; deemed certified in 30 days. Draft SO: statement with establishment details; certification within 60 days.", thresh:"300+ Workers",      forms:["III"] },
        { rule:"Sec 38",      title:"Subsistence Allowance on Suspension",         cls:"so",   codeRef:"Sec 38",    desc:"Suspended worker: inquiry ordinarily within 90 days. Subsistence allowance: 50% of wages for first 90 days; 75% thereafter (if delay not worker's fault).",                                                        thresh:"300+ Workers",      forms:[] }
      ]
    },
    {
      icon: "📋",
      title: "C. Notice of Change & Arbitration (Chapters V–VI)",
      color: "rgba(240,120,50,0.12)",
      items: [
        { rule:"Rule 19",     title:"Notice of Change — FORM-IV (21 Days)",        cls:"con",  codeRef:"Sec 40",    desc:"Employer intending to change service conditions on Third Schedule matters (wages, hours, leave, etc.) MUST give 21 days notice in FORM-IV. Uploaded on designated portal. Displayed conspicuously.",                 thresh:"All Establishments", forms:["IV"] },
        { rule:"Rules 20–22", title:"Voluntary Arbitration — FORM-V & VI",         cls:"arb",  codeRef:"Sec 42",    desc:"Parties may refer dispute to arbitration via FORM-V agreement. Arbitrator written/electronic consent required. Period: 60 days (extendable). Worker authorization via FORM-VI.",                                   thresh:"All Establishments", forms:["V","VI"] }
      ]
    },
    {
      icon: "🚪",
      title: "D. Strikes, Lockouts & Lay-off/Closure (Chapters VIII–X)",
      color: "rgba(240,112,112,0.12)",
      items: [
        { rule:"Rule 25",     title:"Strike Notice — FORM-XI (60 Days)",           cls:"str",  codeRef:"Sec 62",    desc:"Trade Union (signed by Secretary) or 5 elected representatives: 60-day notice in FORM-XI. Copies to Conciliation Officer, CLC(C), Secretary MoLE. NO STRIKE during conciliation/Tribunal proceedings.",          thresh:"All Establishments", forms:["XI"] },
        { rule:"Rule 26",     title:"Lock-out Notice — FORM-XII (60 Days)",        cls:"str",  codeRef:"Sec 62",    desc:"Employer: 60-day notice in FORM-XII to every registered Trade Union. Speed post/electronic. Conspicuously displayed. Copies to Conciliation Officer, CLC(C), Secretary MoLE.",                                   thresh:"All Establishments", forms:["XII"] },
        { rule:"Rules 30–36", title:"Lay-off/Retrenchment/Closure — FORM-XIV",     cls:"lay",  codeRef:"Sec 78,79,80", desc:"300+ workers: LAY-OFF — 15-day prior permission. RETRENCHMENT — 60-day prior permission + 3-month notice. CLOSURE — 90-day prior permission. Government decides in 60 days (deemed granted otherwise).", thresh:"300+ Workers",      forms:["XIV"] },
        { rule:"Rule 37",     title:"Worker Re-skilling Fund — 15 Days Wages",     cls:"lay",  codeRef:"Sec 83",    desc:"On retrenchment: 15 DAYS' LAST DRAWN WAGES electronically within 10 DAYS to CLC(C)/DCLC(C). Disbursed to retrenched worker's bank account within 45 days for re-skilling.",                                      thresh:"All Employers",      forms:[] }
      ]
    },
    {
      icon: "📁",
      title: "E. Records, Compounding & Complaints (Chapter XIV)",
      color: "rgba(96,165,250,0.10)",
      items: [
        { rule:"Rule 47",     title:"Electronic Record Maintenance",                cls:"misc", codeRef:"Sec 99",    desc:"All records, registers, forms, notices, display boards under Rules maintained ELECTRONICALLY. Records comply with retention requirements. Produced to authority on demand.",                                         thresh:"All Establishments", forms:[] },
        { rule:"Rule 38",     title:"Compounding — FORM-XV (50%/75% of Max Fine)", cls:"misc", codeRef:"Sec 89",    desc:"First-time offences: FORM-XV (3 parts). Fine-only offences: 50% of max. Imprisonment up to 1 year: 75% of max fine. 15-day payment deadline. Stops prosecution.",                                                thresh:"All Establishments", forms:["XV"] },
        { rule:"Rules 39, 40", title:"Protected Workers (30 April) & Complaints",  cls:"misc", codeRef:"Sec 90,91", desc:"Trade Union informs employer by 30 APRIL yearly: officers as Protected Workers. Max 1% of workers (min 5, max 100). FORM-XVI complaint by aggrieved employee against Sec 90 violation.",                     thresh:"All Establishments", forms:["XVI"] }
      ]
    }
  ],

  // ============================================================
  // CALENDAR EVENTS
  // ============================================================
  calEvents: [
    { title:"IR Code 2020 — In Force",                       date:"20251121", desc:"S.O. 5320(E) — Industrial Relations Code 2020 brought into force.",                                           id:"ir1" },
    { title:"IR Rules 2026 — Effective",                     date:"20260508", desc:"G.S.R. 342(E) — IR (Central) Rules 2026 (50 Rules, 16 Forms) came into force.",                              id:"ir2" },
    { title:"Protected Workers List — 30 April (Rule 39)",   date:"20270430", desc:"Trade Unions to inform employer by 30 April yearly: officers' list for Protected Worker recognition.",        id:"ir3" },
    { title:"Strike/Lockout 60-Day Notice (Rules 25–26)",    date:"20260801", desc:"Ensure 60-day FORM-XI/XII notice before any strike or lockout.",                                              id:"ir4" },
    { title:"Re-skilling Fund Transfer (Rule 37)",           date:"20270101", desc:"On retrenchment: 15 days wages within 10 days to CLC(C) accounts.",                                          id:"ir5" },
    { title:"Trade Union Annual Returns (Sec 26)",           date:"20270228", desc:"Trade Unions annual general statement to Registrar for year ending 31 December.",                             id:"ir6" }
  ],

  // ============================================================
  // TIMELINE
  // ============================================================
  timeline: [
    { date:"28 Sep 2020",     title:"Industrial Relations Code, 2020 Enacted",               sub:"Act No. 35 of 2020 — consolidates 3 earlier laws: Trade Unions Act 1926, Industrial Employment (Standing Orders) Act 1946, Industrial Disputes Act 1947.",                                                              color:"#9B72E8" },
    { date:"21 Nov 2025",     title:"Code Brought into Force — S.O. 5320(E)",                sub:"Industrial Relations Code 2020 brought into force on 21 November 2025.",                                                                                                                                                color:"#2ECC9A" },
    { date:"30 Dec 2025",     title:"Draft Central Rules Published — G.S.R. 930(E)",         sub:"Draft IR (Central) Rules published with 30-day comment window.",                                                                                                                                                         color:"#E8A020" },
    { date:"8 May 2026",      title:"✅ Final Rules Notified — G.S.R. 342(E)",               sub:"50 Rules across 13 Chapters, 16 Forms (FORM-I to XVI). Effective from date of publication.",                                                                                                                             color:"#2ECC9A" },
    { date:"30 Apr (Annual)", title:"📋 Trade Union Protected Workers List (Rule 39)",       sub:"Trade Unions to inform employer by 30 April: officers' list for Protected Worker recognition. Max 1% of workers.",                                                                                                       color:"#2E6FED" },
    { date:"15/60/90 Days",   title:"📁 Permission Window — 300+ Workers (Rules 30–36)",     sub:"Lay-off: 15 days; Retrenchment: 60 days; Closure: 90 days in FORM-XIV to Central Government.",                                                                                                                          color:"#F07070" }
  ]
};